-- MySQL Script generated by MySQL Workbench
-- 06/17/16 22:07:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema prorim
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema prorim
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `prorim` DEFAULT CHARACTER SET latin1 ;
USE `prorim` ;

-- -----------------------------------------------------
-- Table `prorim`.`auditoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prorim`.`auditoria` (
  `usuario` VARCHAR(100) NULL DEFAULT NULL,
  `acao` VARCHAR(100) NULL DEFAULT NULL,
  `dt` DATE NULL DEFAULT NULL,
  `hora` TIME NULL DEFAULT NULL,
  `codigo` INT(11) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `prorim`.`dotacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prorim`.`dotacao` (
  `Cod_Despesa` INT(7) NOT NULL AUTO_INCREMENT,
  `Despesa` VARCHAR(45) NULL DEFAULT NULL,
  `Reduzida` VARCHAR(45) NULL DEFAULT NULL,
  `Programa` VARCHAR(45) NULL DEFAULT NULL,
  `Acao` VARCHAR(45) NULL DEFAULT NULL COMMENT 'não foi renomeada mas trata-se codigos de aplicação',
  PRIMARY KEY (`Cod_Despesa`))
ENGINE = InnoDB
AUTO_INCREMENT = 455
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `prorim`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prorim`.`fornecedor` (
  `Cod_fornecedor` INT(6) NOT NULL AUTO_INCREMENT,
  `Nome_fornecedor` VARCHAR(200) NULL DEFAULT NULL,
  `Tipo_fornecedor` CHAR(2) NULL DEFAULT NULL,
  `Numero_tipo` VARCHAR(20) NULL DEFAULT NULL,
  `Tipo_logradouro` VARCHAR(45) NULL DEFAULT NULL,
  `End_fornecedor` VARCHAR(200) NULL DEFAULT NULL,
  `Nr_endereco` VARCHAR(10) NULL DEFAULT NULL,
  `Bairro_fornecedor` VARCHAR(45) NULL DEFAULT NULL,
  `Cidade_fornecedor` VARCHAR(45) NULL DEFAULT NULL,
  `UF_fornecedor` CHAR(2) NULL DEFAULT NULL,
  `Fone1_fornecedor` VARCHAR(20) NULL DEFAULT NULL,
  `Fone2_fornecedor` VARCHAR(20) NULL DEFAULT NULL,
  `Email_fornecedor` VARCHAR(100) NULL DEFAULT NULL,
  `Site_fornecedor` VARCHAR(100) NULL DEFAULT NULL,
  `Contato` VARCHAR(200) NULL DEFAULT NULL,
  `Email_contato` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`Cod_fornecedor`))
ENGINE = InnoDB
AUTO_INCREMENT = 100209
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `prorim`.`notas_fiscais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prorim`.`notas_fiscais` (
  `Cod_notas_fiscais` INT(11) NOT NULL AUTO_INCREMENT,
  `Cod_rim` INT(11) NOT NULL,
  `Cod_fornecedor` INT(11) NOT NULL,
  `Num_NotaFiscal` VARCHAR(100) NULL DEFAULT NULL,
  `Data_NotaFiscal` VARCHAR(10) NULL DEFAULT NULL,
  `Valor_NotaFiscal` VARCHAR(50) NULL DEFAULT NULL,
  `Setor_Enviado` VARCHAR(45) NULL DEFAULT NULL,
  `Data_Envio` VARCHAR(10) NULL DEFAULT NULL,
  `Situacao` VARCHAR(4) NULL DEFAULT NULL,
  `DataNotaSQL` DATE NULL DEFAULT NULL,
  `fornecedor_Cod_fornecedor` INT(6) NOT NULL,
  PRIMARY KEY (`Cod_notas_fiscais`, `fornecedor_Cod_fornecedor`),
  INDEX `fk_notas_fiscais_fornecedor1_idx` (`fornecedor_Cod_fornecedor` ASC),
  CONSTRAINT `fk_notas_fiscais_fornecedor1`
    FOREIGN KEY (`fornecedor_Cod_fornecedor`)
    REFERENCES `prorim`.`fornecedor` (`Cod_fornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1168
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `prorim`.`unidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prorim`.`unidade` (
  `Cod_unidade` INT(6) NOT NULL AUTO_INCREMENT,
  `Nome_unidade` VARCHAR(200) NOT NULL,
  `Tipo_unidade` VARCHAR(45) NULL DEFAULT NULL,
  `End_unidade` VARCHAR(200) NULL DEFAULT NULL,
  `Nr_endereco` VARCHAR(10) NULL DEFAULT NULL,
  `Bairro_unidade` VARCHAR(45) NULL DEFAULT NULL,
  `Cidade_unidade` VARCHAR(45) NULL DEFAULT NULL,
  `UF_unidade` CHAR(2) NULL DEFAULT NULL,
  `Fone1_unidade` VARCHAR(20) NULL DEFAULT NULL,
  `Fone2_unidade` VARCHAR(20) NULL DEFAULT NULL,
  `Resp_unidade` VARCHAR(200) NULL DEFAULT NULL,
  `Fone_contato` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`Cod_unidade`))
ENGINE = InnoDB
AUTO_INCREMENT = 70
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `prorim`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prorim`.`usuario` (
  `Cod_usuario` INT(6) NOT NULL AUTO_INCREMENT,
  `Nome_usuario` VARCHAR(200) NOT NULL,
  `Login_usuario` VARCHAR(16) NOT NULL,
  `Senha_usuario` VARCHAR(10) NOT NULL,
  `Setor_usuario` VARCHAR(100) NULL DEFAULT NULL,
  `Email_usuario` VARCHAR(200) NULL DEFAULT NULL,
  `Tipo_usuario` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`Cod_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `prorim`.`rim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prorim`.`rim` (
  `Cod_rim` INT(7) NOT NULL AUTO_INCREMENT,
  `Nome_Unidade` VARCHAR(200) NULL DEFAULT NULL,
  `Descricao` VARCHAR(400) NULL DEFAULT NULL,
  `Dotacao` VARCHAR(100) NULL DEFAULT NULL,
  `Tipo_RIM` VARCHAR(5) NULL DEFAULT NULL,
  `Cetil` VARCHAR(45) NOT NULL,
  `DataCetil` VARCHAR(15) NULL DEFAULT NULL,
  `DataCetilSQL` DATE NULL DEFAULT NULL,
  `ValorEstimado` VARCHAR(40) NULL DEFAULT NULL,
  `ValorReal` VARCHAR(40) NULL DEFAULT NULL,
  `Processo` VARCHAR(10) NULL DEFAULT NULL,
  `ano_processo` YEAR NOT NULL,
  `ProcessoContabil` VARCHAR(10) NULL DEFAULT NULL,
  `ano_processo_contabil` YEAR NOT NULL,
  `Contabilidade` VARCHAR(10) NULL DEFAULT NULL,
  `OrdenadorAss` VARCHAR(10) NULL DEFAULT NULL,
  `ComprasPrim` VARCHAR(10) NULL DEFAULT NULL,
  `OrdenadorEmpenho` VARCHAR(10) NULL DEFAULT NULL,
  `ComprasSeg` VARCHAR(10) NULL DEFAULT NULL,
  `Dipe` VARCHAR(10) NULL DEFAULT NULL,
  `Cadastrante` VARCHAR(200) NULL DEFAULT NULL,
  `DataCadastro` VARCHAR(15) NULL DEFAULT NULL,
  `Observacao` VARCHAR(500) NULL DEFAULT NULL,
  `Atendida` VARCHAR(15) NULL DEFAULT NULL,
  `Concluida` VARCHAR(15) NULL DEFAULT NULL,
  `unidade_Cod_unidade` INT(6) NOT NULL,
  `usuario_Cod_usuario` INT(6) NOT NULL,
  PRIMARY KEY (`Cod_rim`, `unidade_Cod_unidade`, `usuario_Cod_usuario`),
  INDEX `fk_rim_unidade1_idx` (`unidade_Cod_unidade` ASC),
  INDEX `fk_rim_usuario1_idx` (`usuario_Cod_usuario` ASC),
  CONSTRAINT `fk_rim_unidade1`
    FOREIGN KEY (`unidade_Cod_unidade`)
    REFERENCES `prorim`.`unidade` (`Cod_unidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rim_usuario1`
    FOREIGN KEY (`usuario_Cod_usuario`)
    REFERENCES `prorim`.`usuario` (`Cod_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4114
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `prorim`.`rim_has_dotacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prorim`.`rim_has_dotacao` (
  `Codigo` INT(7) NOT NULL AUTO_INCREMENT,
  `Cod_rim` INT(7) NOT NULL,
  `Cod_despesa` INT(7) NOT NULL,
  `Cetil` VARCHAR(45) NOT NULL,
  `empenho` VARCHAR(45) NULL DEFAULT NULL,
  `dataempenho` VARCHAR(10) NULL DEFAULT NULL,
  `valorempenho` VARCHAR(40) NULL DEFAULT NULL,
  `autorizacao` VARCHAR(10) NULL DEFAULT NULL,
  `dataAF` VARCHAR(10) NULL DEFAULT NULL,
  `valorAF` VARCHAR(40) NULL DEFAULT NULL,
  `nome_fornecedor` VARCHAR(45) NULL DEFAULT NULL,
  `tipo_rim` CHAR(3) NULL DEFAULT NULL,
  `dataempenhoSQL` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 2321
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `prorim`.`rim_has_fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prorim`.`rim_has_fornecedor` (
  `Cod_rim` INT(6) NOT NULL,
  `Cod_fornecedor` INT(7) NOT NULL,
  PRIMARY KEY (`Cod_rim`, `Cod_fornecedor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `prorim`.`rim_has_veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prorim`.`rim_has_veiculo` (
  `cod_rim` INT(7) NOT NULL,
  `cod_seq_veiculo` INT(6) NOT NULL,
  PRIMARY KEY (`cod_rim`, `cod_seq_veiculo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `prorim`.`veiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prorim`.`veiculos` (
  `Cod_seq_veiculo` INT(6) NOT NULL AUTO_INCREMENT,
  `Setor_gestor` VARCHAR(45) NULL DEFAULT NULL,
  `Placa` VARCHAR(8) NOT NULL,
  `Lotacao` VARCHAR(45) NULL DEFAULT NULL,
  `Marca` VARCHAR(45) NULL DEFAULT NULL,
  `Modelo` VARCHAR(45) NULL DEFAULT NULL,
  `Ano` VARCHAR(4) NULL DEFAULT NULL,
  `Cod_unidade` INT(6) NOT NULL,
  PRIMARY KEY (`Cod_seq_veiculo`))
ENGINE = InnoDB
AUTO_INCREMENT = 83
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `prorim`.`fornecedor_has_rim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prorim`.`fornecedor_has_rim` (
  `fornecedor_Cod_fornecedor` INT(6) NOT NULL,
  `rim_Cod_rim` INT(7) NOT NULL,
  PRIMARY KEY (`fornecedor_Cod_fornecedor`, `rim_Cod_rim`),
  INDEX `fk_fornecedor_has_rim_rim1_idx` (`rim_Cod_rim` ASC),
  INDEX `fk_fornecedor_has_rim_fornecedor1_idx` (`fornecedor_Cod_fornecedor` ASC),
  CONSTRAINT `fk_fornecedor_has_rim_fornecedor1`
    FOREIGN KEY (`fornecedor_Cod_fornecedor`)
    REFERENCES `prorim`.`fornecedor` (`Cod_fornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fornecedor_has_rim_rim1`
    FOREIGN KEY (`rim_Cod_rim`)
    REFERENCES `prorim`.`rim` (`Cod_rim`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `prorim`.`rim_has_dotacao1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prorim`.`rim_has_dotacao1` (
  `rim_Cod_rim` INT(7) NOT NULL,
  `dotacao_Cod_Despesa` INT(7) NOT NULL,
  PRIMARY KEY (`rim_Cod_rim`, `dotacao_Cod_Despesa`),
  INDEX `fk_rim_has_dotacao1_dotacao1_idx` (`dotacao_Cod_Despesa` ASC),
  INDEX `fk_rim_has_dotacao1_rim1_idx` (`rim_Cod_rim` ASC),
  CONSTRAINT `fk_rim_has_dotacao1_rim1`
    FOREIGN KEY (`rim_Cod_rim`)
    REFERENCES `prorim`.`rim` (`Cod_rim`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rim_has_dotacao1_dotacao1`
    FOREIGN KEY (`dotacao_Cod_Despesa`)
    REFERENCES `prorim`.`dotacao` (`Cod_Despesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `prorim`.`veiculos_has_unidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prorim`.`veiculos_has_unidade` (
  `veiculos_Cod_seq_veiculo` INT(6) NOT NULL,
  `unidade_Cod_unidade` INT(6) NOT NULL,
  PRIMARY KEY (`veiculos_Cod_seq_veiculo`, `unidade_Cod_unidade`),
  INDEX `fk_veiculos_has_unidade_unidade1_idx` (`unidade_Cod_unidade` ASC),
  INDEX `fk_veiculos_has_unidade_veiculos1_idx` (`veiculos_Cod_seq_veiculo` ASC),
  CONSTRAINT `fk_veiculos_has_unidade_veiculos1`
    FOREIGN KEY (`veiculos_Cod_seq_veiculo`)
    REFERENCES `prorim`.`veiculos` (`Cod_seq_veiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_veiculos_has_unidade_unidade1`
    FOREIGN KEY (`unidade_Cod_unidade`)
    REFERENCES `prorim`.`unidade` (`Cod_unidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

USE `prorim`;

DELIMITER $$
USE `prorim`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `prorim`.`auditoria_insert`
AFTER INSERT ON `prorim`.`rim`
FOR EACH ROW
BEGIN
   INSERT INTO auditoria SET 
     codigo = new.Cod_rim,
     usuario = user(),
     acao = 'cadastrou',
     dt = Curdate(),
     hora = Curtime();
 END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
