/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ConnectionDB;
import controller.ControllerUnidade;
import controller.ControllerUsuario;
import controller.ModelTabela;
import jacontrol.Classes.WebServiceCep;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import model.ModelUnidade;
import model.ModelUsuario;

/**
 *
 * @author 64033
 */
public class JFrameUnidade extends javax.swing.JFrame {

    ConnectionDB conecta = new ConnectionDB();
    ModelUnidade unidade = new ModelUnidade();
    ControllerUnidade uni = new ControllerUnidade();
    int flagUnidade= 0;
    /**
     * Creates new form JFrameUnidade
     */
    public JFrameUnidade() {
        initComponents();
        setDefaultCloseOperation(JFrameUnidade.HIDE_ON_CLOSE);

        desabilitaCamposdeTexto();
        conecta.conexao();
        preencherTabela("select * from unidade order by Cod_unidade");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jPanelEndereco = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        comboBoxUf = new javax.swing.JComboBox<>();
        cmbTipo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtCodUnidade = new javax.swing.JTextField();
        txtNomeUnidade = new javax.swing.JTextField();
        txtLogradouro = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        txtCep = new javax.swing.JTextField();
        txtFone1 = new javax.swing.JTextField();
        txtResponsavel = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        txtFone2 = new javax.swing.JTextField();
        jPanelStart = new javax.swing.JPanel();
        buttonOK = new javax.swing.JButton();
        buttonCancelar = new javax.swing.JButton();
        buttonSair = new javax.swing.JButton();
        rbNovo = new javax.swing.JRadioButton();
        rbAlterar = new javax.swing.JRadioButton();
        rbExcluir = new javax.swing.JRadioButton();
        ButtonRefresh = new javax.swing.JButton();
        jPanelFiltros = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtUnidadePesquisa = new javax.swing.JTextField();
        txtCodigoPesquisa = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        buttonPesquisaUnidade = new javax.swing.JButton();
        buttonRefresh = new javax.swing.JButton();
        jPanelOrdenacao = new javax.swing.JPanel();
        jRadioButtonCodigo = new javax.swing.JRadioButton();
        jRadioButtonNome = new javax.swing.JRadioButton();
        jRadioButtonContato = new javax.swing.JRadioButton();
        jScrollPaneTabela = new javax.swing.JScrollPane();
        jTableUnidade = new javax.swing.JTable();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Movimentação e Pesquisa de Unidades");

        jPanelEndereco.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Código");

        jLabel2.setText("Unidade Setor");

        jLabel3.setText("Tipo");

        jLabel4.setText("Logradouro");

        jLabel5.setText("Nº");

        jLabel6.setText("Bairro");

        jLabel7.setText("Cidade");

        comboBoxUf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO" }));

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alameda", "Área", "Avenida", "Campo", "Chácara", "Estrada", "Ladeira", "Loteamento", "Morro", "Parque", "Passarela", "Praça", "Quadra", "Rodovia", "Rua", "Travessa", "Via" }));
        cmbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoActionPerformed(evt);
            }
        });

        jLabel8.setText("U.F");

        jLabel9.setText("C.E.P");

        jLabel10.setText("Telefone 1");

        jLabel11.setText("Telefone 2");

        jLabel12.setText("Responsável | Contato");

        jLabel13.setText("Tel./Celular");

        txtBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBairroActionPerformed(evt);
            }
        });

        txtCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCidadeActionPerformed(evt);
            }
        });

        txtCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEnderecoLayout = new javax.swing.GroupLayout(jPanelEndereco);
        jPanelEndereco.setLayout(jPanelEnderecoLayout);
        jPanelEnderecoLayout.setHorizontalGroup(
            jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                        .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3)
                                .addComponent(jLabel1)
                                .addComponent(cmbTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCodUnidade)
                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5))
                        .addGap(81, 81, 81)
                        .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtLogradouro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBairro, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeUnidade)))
                    .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                        .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                                        .addComponent(txtCep)
                                        .addGap(73, 73, 73))
                                    .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                                        .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel9))
                                        .addGap(53, 53, 53)))
                                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(txtFone1, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)))
                            .addComponent(txtResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11)
                            .addComponent(txtFone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEnderecoLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEnderecoLayout.createSequentialGroup()
                        .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboBoxUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(14, 14, 14))
        );

        jPanelEnderecoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtFone1, txtFone2});

        jPanelEnderecoLayout.setVerticalGroup(
            jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(3, 3, 3)
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                        .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNumero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelEnderecoLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(comboBoxUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel10))
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelStart.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buttonOK.setText("OK");
        buttonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOKActionPerformed(evt);
            }
        });

        buttonCancelar.setText("Cancelar");
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });

        buttonSair.setText("Sair");
        buttonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSairActionPerformed(evt);
            }
        });

        rbNovo.setText("Novo");
        rbNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbNovoMouseClicked(evt);
            }
        });
        rbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNovoActionPerformed(evt);
            }
        });

        rbAlterar.setText("Alterar");
        rbAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbAlterarMouseClicked(evt);
            }
        });
        rbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAlterarActionPerformed(evt);
            }
        });

        rbExcluir.setText("Excluir");
        rbExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbExcluirMouseClicked(evt);
            }
        });
        rbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbExcluirActionPerformed(evt);
            }
        });

        ButtonRefresh.setText("Refresh");

        javax.swing.GroupLayout jPanelStartLayout = new javax.swing.GroupLayout(jPanelStart);
        jPanelStart.setLayout(jPanelStartLayout);
        jPanelStartLayout.setHorizontalGroup(
            jPanelStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelStartLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanelStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelStartLayout.createSequentialGroup()
                        .addComponent(rbNovo)
                        .addGap(8, 8, 8))
                    .addComponent(rbExcluir)
                    .addComponent(rbAlterar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanelStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonCancelar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonOK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonRefresh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        jPanelStartLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ButtonRefresh, buttonCancelar, buttonOK});

        jPanelStartLayout.setVerticalGroup(
            jPanelStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStartLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(rbNovo)
                .addGap(29, 29, 29)
                .addComponent(rbAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbExcluir)
                .addGap(62, 62, 62))
            .addGroup(jPanelStartLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(buttonOK)
                .addGap(18, 18, 18)
                .addComponent(buttonCancelar)
                .addGap(18, 18, 18)
                .addComponent(ButtonRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonSair)
                .addGap(28, 28, 28))
        );

        jPanelStartLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ButtonRefresh, buttonCancelar, buttonOK});

        jPanelFiltros.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3), "Filtros", javax.swing.border.TitledBorder.TRAILING, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel14.setText("Código");

        txtUnidadePesquisa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUnidadePesquisaFocusGained(evt);
            }
        });

        txtCodigoPesquisa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodigoPesquisaFocusGained(evt);
            }
        });
        txtCodigoPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoPesquisaActionPerformed(evt);
            }
        });

        jLabel15.setText("Unidade");

        buttonPesquisaUnidade.setText("Pesquisa");
        buttonPesquisaUnidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPesquisaUnidadeActionPerformed(evt);
            }
        });

        buttonRefresh.setText("Refresh");
        buttonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFiltrosLayout = new javax.swing.GroupLayout(jPanelFiltros);
        jPanelFiltros.setLayout(jPanelFiltrosLayout);
        jPanelFiltrosLayout.setHorizontalGroup(
            jPanelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFiltrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(txtCodigoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(txtUnidadePesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonPesquisaUnidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelFiltrosLayout.setVerticalGroup(
            jPanelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFiltrosLayout.createSequentialGroup()
                .addGroup(jPanelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFiltrosLayout.createSequentialGroup()
                        .addGroup(jPanelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUnidadePesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelFiltrosLayout.createSequentialGroup()
                        .addComponent(buttonPesquisaUnidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonRefresh)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelOrdenacao.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3), "Opções de Ordenação"));

        jRadioButtonCodigo.setText("Código");

        jRadioButtonNome.setText("Nome");

        jRadioButtonContato.setText("Contato");

        javax.swing.GroupLayout jPanelOrdenacaoLayout = new javax.swing.GroupLayout(jPanelOrdenacao);
        jPanelOrdenacao.setLayout(jPanelOrdenacaoLayout);
        jPanelOrdenacaoLayout.setHorizontalGroup(
            jPanelOrdenacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOrdenacaoLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jRadioButtonCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonNome, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jRadioButtonContato, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanelOrdenacaoLayout.setVerticalGroup(
            jPanelOrdenacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOrdenacaoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelOrdenacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonCodigo)
                    .addComponent(jRadioButtonNome)
                    .addComponent(jRadioButtonContato))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jScrollPaneTabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPaneTabelaMouseClicked(evt);
            }
        });

        jTableUnidade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableUnidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableUnidadeMouseClicked(evt);
            }
        });
        jScrollPaneTabela.setViewportView(jTableUnidade);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneTabela)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelFiltros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelOrdenacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelOrdenacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelFiltros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPaneTabela, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoActionPerformed

    private void txtCodigoPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoPesquisaActionPerformed

    private void txtBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBairroActionPerformed

    private void txtCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCidadeActionPerformed

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed

        habilitaRbButtons();
        LimpaCamposTexto();
        desabilitaCamposdeTexto();
        desmarcarRbButtons();
        buttonOK.setEnabled(false);
        buttonCancelar.setEnabled(false);

    }//GEN-LAST:event_buttonCancelarActionPerformed

    private void buttonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOKActionPerformed
        
        unidade.setUnidade(txtNomeUnidade.getText());
        unidade.setEndereco(txtLogradouro.getText());
        unidade.setNumero(txtNumero.getText());
        unidade.setBairro(txtBairro.getText());
        unidade.setCidade(txtCidade.getText());
        unidade.setUfUnidade(comboBoxUf.getSelectedItem().toString());
        unidade.setTelefone1(txtFone1.getText());
        unidade.setTelefone2(txtFone2.getText());
        unidade.setResponsavel(txtResponsavel.getText());
        unidade.setFoneContato(txtCelular.getText());
        unidade.setTipo(cmbTipo.getSelectedItem().toString());
        

// TODO add your handling code here:
        if (rbNovo.isSelected()) {
            uni.InserirUnidade(unidade);
        } else if (rbExcluir.isSelected()) {
            if (!"".equals(txtCodUnidade.getText())) {
                unidade.setCodUnidade(Integer.valueOf(txtCodUnidade.getText()));
                uni.ExcluirUnidade(unidade);
            } else {
                JOptionPane.showMessageDialog(null, "Escolha na tabela o item a ser excluído.");
            }
        } else if (!"".equals(txtCodUnidade.getText())) {
            unidade.setCodUnidade(Integer.valueOf(txtCodUnidade.getText()));
            uni.AlterarUnidade(unidade);
        } else {
            JOptionPane.showMessageDialog(null, "Escolha na tabela o item a ser alterado.");
        }
    }//GEN-LAST:event_buttonOKActionPerformed

    private void rbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNovoActionPerformed
        desabilitaRdButtons();
        habilitaCamposdeTexto();
        rbExcluir.setSelected(false);
        rbAlterar.setSelected(false);
    }//GEN-LAST:event_rbNovoActionPerformed

    private void txtCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCepActionPerformed
        buscaCep();
    }//GEN-LAST:event_txtCepActionPerformed

    private void rbNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbNovoMouseClicked
        // TODO add your handling code here:
        rbExcluir.setSelected(false);
        rbAlterar.setSelected(false);
        buttonOK.setEnabled(true);
        buttonCancelar.setEnabled(true);
    }//GEN-LAST:event_rbNovoMouseClicked

    private void rbAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbAlterarMouseClicked
        // TODO add your handling code here:
        rbExcluir.setSelected(false);
        rbNovo.setSelected(false);
        buttonOK.setEnabled(true);
        buttonCancelar.setEnabled(true);
        
    }//GEN-LAST:event_rbAlterarMouseClicked

    private void rbExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbExcluirMouseClicked
        rbNovo.setSelected(false);
        rbAlterar.setSelected(false);
        buttonOK.setEnabled(true);
        buttonCancelar.setEnabled(true);

    }//GEN-LAST:event_rbExcluirMouseClicked

    private void jScrollPaneTabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPaneTabelaMouseClicked


    }//GEN-LAST:event_jScrollPaneTabelaMouseClicked

    private void jTableUnidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableUnidadeMouseClicked
        try {
            // TODO add your handling code here:
            //Preenche os Campos de Texto correspondentes ao clicar numa linha do JTable
            String codigoUnidade = "" + jTableUnidade.getValueAt(jTableUnidade.getSelectedRow(), 0);
            conecta.conexao();
            conecta.executaSQL("Select * from unidade where cod_unidade='" + codigoUnidade + "'");
            conecta.rs.first();
            txtCodUnidade.setText(String.valueOf(conecta.rs.getInt("Cod_unidade")));
            txtNomeUnidade.setText(String.valueOf(conecta.rs.getString("Nome_unidade")));
            //cmbTipo.setText(String.valueOf(conecta.rs.getString("Nome_unidade")));
            txtLogradouro.setText(String.valueOf(conecta.rs.getString("End_unidade")));
            txtNumero.setText(String.valueOf(conecta.rs.getString("Nr_endereco")));
            txtBairro.setText(String.valueOf(conecta.rs.getString("Bairro_unidade")));
            txtCidade.setText(String.valueOf(conecta.rs.getString("Cidade_unidade")));
            //comboBoxUf.setText(String.valueOf(conecta.rs.getString("UF_unidade")));
            txtFone1.setText(String.valueOf(conecta.rs.getString("Fone1_unidade")));
            txtFone2.setText(String.valueOf(conecta.rs.getString("Fone2_unidade")));
            txtResponsavel.setText(String.valueOf(conecta.rs.getString("Resp_unidade")));
            txtCelular.setText(String.valueOf(conecta.rs.getString("Fone_contato")));

            //conecta.desconectar();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao capturar dados da linha selecionada" + ex.getMessage());
        }
    }//GEN-LAST:event_jTableUnidadeMouseClicked

    private void rbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAlterarActionPerformed
        // TODO add your handling code here:
        
        rbExcluir.setSelected(false);
        rbNovo.setSelected(false);
        buttonOK.setEnabled(true);
        buttonCancelar.setEnabled(true);
        
        JOptionPane.showMessageDialog(null, "Dê duplo clique com o mouse na linha da tabela acima\n correspondente à Unidade que você quer alterar");
        
    }//GEN-LAST:event_rbAlterarActionPerformed

    private void rbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbExcluirActionPerformed
        
// TODO add your handling code here:
        rbAlterar.setSelected(false);
        rbNovo.setSelected(false);
        buttonOK.setEnabled(true);
        buttonCancelar.setEnabled(true);
        
        JOptionPane.showMessageDialog(null, "Dê duplo clique com o mouse na linha da tabela acima\n correspondente à Unidade que você quer excluir");
        
    }//GEN-LAST:event_rbExcluirActionPerformed

    private void buttonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonSairActionPerformed

    private void buttonPesquisaUnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPesquisaUnidadeActionPerformed
        // TODO add your handling code here:
        
        switch (flagUnidade) {
            case 1:
                preencherTabela("Select * from unidade order by cod_unidade");
                habilitaCamposdeTexto();
                txtCodigoPesquisa.setText(txtCodigoPesquisa.getText().toUpperCase());
                String pesquisaporcodigorim = txtCodigoPesquisa.getText();

                if (pesquisaporcodigorim.length() > 0) {
                    for (int i = 0; i < jTableUnidade.getRowCount(); i++) {
                        if (!pesquisaporcodigorim.equals(jTableUnidade.getValueAt(i, 0).toString())) {
                        } else {
                            preencherTabela("Select * From unidade where Cod_unidade='" + pesquisaporcodigorim + "'");
                        }
                    }
                }
            break;
            case 2:
                preencherTabela("Select * from unidade order by cod_unidade");
                habilitaCamposdeTexto();
                txtUnidadePesquisa.setText(txtUnidadePesquisa.getText().toUpperCase());
                String pesquisaporunidade = txtUnidadePesquisa.getText();

                if (pesquisaporunidade.length() > 0) {
                    for (int i = 0; i < jTableUnidade.getRowCount(); i++) {
                        if (!pesquisaporunidade.equals(jTableUnidade.getValueAt(i, 1).toString())) {
                        } else {
                            preencherTabela("Select * From unidade where Nome_unidade='%" + pesquisaporunidade + "%'");
                        }
                    }
                }
                break;
        }               
        
    }//GEN-LAST:event_buttonPesquisaUnidadeActionPerformed

    private void txtCodigoPesquisaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoPesquisaFocusGained
        // TODO add your handling code here:
        flagUnidade=1;
        txtUnidadePesquisa.setText("");
        
    }//GEN-LAST:event_txtCodigoPesquisaFocusGained

    private void txtUnidadePesquisaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUnidadePesquisaFocusGained
        // TODO add your handling code here:
        flagUnidade=2;
        txtCodigoPesquisa.setText("");
        
    }//GEN-LAST:event_txtUnidadePesquisaFocusGained

    private void buttonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRefreshActionPerformed
        // TODO add your handling code here:
        
        preencherTabela("Select * from unidade order by Cod_unidade");
        
    }//GEN-LAST:event_buttonRefreshActionPerformed
    public void buscaCep() {
        //Faz a busca para o cep 58043-280
        WebServiceCep webServiceCep = WebServiceCep.searchCep(txtCep.getText());
        //A ferramenta de busca ignora qualquer caracter que n?o seja n?mero.

        //caso a busca ocorra bem, imprime os resultados.
        if (webServiceCep.wasSuccessful()) {
            txtLogradouro.setText(webServiceCep.getLogradouroFull());
            txtCidade.setText(webServiceCep.getCidade());
            txtBairro.setText(webServiceCep.getBairro());
            comboBoxUf.setSelectedItem(webServiceCep.getUf());
            System.out.println("Cep: " + webServiceCep.getCep());
            System.out.println("Logradouro: " + webServiceCep.getLogradouroFull());
            System.out.println("Bairro: " + webServiceCep.getBairro());
            System.out.println("Cidade: "
                    + webServiceCep.getCidade() + "/" + webServiceCep.getUf());

            //caso haja problemas imprime as exce??es.
        } else {
            JOptionPane.showMessageDialog(null, "Erro numero: " + webServiceCep.getResulCode());

            JOptionPane.showMessageDialog(null, "Descrição do erro: " + webServiceCep.getResultText());
        }
    }

    public void preencherTabela(String SQL) {

        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Código", "Unidade", "Tipo", "Endereço", "Número", "Bairro", "Cidade", "UF", "Telefone1", "Telefone2", "Responsavel", "TelContato"};

        conecta.executaSQL(SQL);

        try {
            conecta.rs.first();//"update usuario set Nome_usuario=?,Login_usuario=?,Senha_usuario=?,Setor_usuario=?,Email_usuario=?,Tipo_usuario=
            do {
                dados.add(new Object[]{conecta.rs.getInt("Cod_unidade"), conecta.rs.getString("Nome_unidade"), conecta.rs.getString("Tipo_unidade"), conecta.rs.getString("End_unidade"), conecta.rs.getString("Nr_endereco"), conecta.rs.getString("Bairro_unidade"), conecta.rs.getString("Cidade_unidade"), conecta.rs.getString("UF_unidade"), conecta.rs.getString("Fone1_unidade"), conecta.rs.getString("Fone2_unidade"), conecta.rs.getString("Resp_unidade"), conecta.rs.getString("Fone_contato")});
            } while (conecta.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Informação não encontrada.\n" + ex.getMessage());
        }

        //Criando a Tabela
        ModelTabela modelo = new ModelTabela(dados, colunas);
        jTableUnidade.setModel(modelo);
        jTableUnidade.getColumnModel().getColumn(0).setPreferredWidth(120);
        jTableUnidade.getColumnModel().getColumn(0).setResizable(false);
        jTableUnidade.getColumnModel().getColumn(1).setPreferredWidth(120);
        jTableUnidade.getColumnModel().getColumn(1).setResizable(false);
        jTableUnidade.getColumnModel().getColumn(2).setPreferredWidth(120);
        jTableUnidade.getColumnModel().getColumn(2).setResizable(false);
        jTableUnidade.getColumnModel().getColumn(3).setPreferredWidth(120);
        jTableUnidade.getColumnModel().getColumn(3).setResizable(false);
        jTableUnidade.getColumnModel().getColumn(4).setPreferredWidth(120);
        jTableUnidade.getColumnModel().getColumn(4).setResizable(false);
        jTableUnidade.getColumnModel().getColumn(5).setPreferredWidth(120);
        jTableUnidade.getColumnModel().getColumn(5).setResizable(false);
        jTableUnidade.getColumnModel().getColumn(6).setPreferredWidth(120);
        jTableUnidade.getColumnModel().getColumn(6).setResizable(false);
        jTableUnidade.getColumnModel().getColumn(7).setPreferredWidth(120);
        jTableUnidade.getColumnModel().getColumn(7).setResizable(false);
        jTableUnidade.getTableHeader().setReorderingAllowed(false);
        jTableUnidade.setAutoResizeMode(jTableUnidade.AUTO_RESIZE_OFF);
        jTableUnidade.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameUnidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameUnidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameUnidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameUnidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameUnidade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonRefresh;
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JButton buttonOK;
    private javax.swing.JButton buttonPesquisaUnidade;
    private javax.swing.JButton buttonRefresh;
    private javax.swing.JButton buttonSair;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JComboBox<String> comboBoxUf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelEndereco;
    private javax.swing.JPanel jPanelFiltros;
    private javax.swing.JPanel jPanelOrdenacao;
    private javax.swing.JPanel jPanelStart;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButtonCodigo;
    private javax.swing.JRadioButton jRadioButtonContato;
    private javax.swing.JRadioButton jRadioButtonNome;
    private javax.swing.JScrollPane jScrollPaneTabela;
    private javax.swing.JTable jTableUnidade;
    private javax.swing.JRadioButton rbAlterar;
    private javax.swing.JRadioButton rbExcluir;
    private javax.swing.JRadioButton rbNovo;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCodUnidade;
    private javax.swing.JTextField txtCodigoPesquisa;
    private javax.swing.JTextField txtFone1;
    private javax.swing.JTextField txtFone2;
    private javax.swing.JTextField txtLogradouro;
    private javax.swing.JTextField txtNomeUnidade;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtResponsavel;
    private javax.swing.JTextField txtUnidadePesquisa;
    // End of variables declaration//GEN-END:variables
private void desabilitaRdButtons() {

        jRadioButtonCodigo.setEnabled(false);
        jRadioButtonNome.setEnabled(false);
        jRadioButtonContato.setEnabled(false);

    }

    private void habilitaRdButtons() {
        buttonOK.setEnabled(true);
        buttonCancelar.setEnabled(true);
        buttonSair.setEnabled(true);
    }

    private void desabilitaCamposdeTexto() {
        txtCodUnidade.setEnabled(false);
        txtNomeUnidade.setEnabled(false);
        txtLogradouro.setEnabled(false);
        txtNumero.setEnabled(false);
        txtBairro.setEnabled(false);
        txtCidade.setEnabled(false);
        txtCep.setEnabled(false);
        txtFone1.setEnabled(false);
        txtFone2.setEnabled(false);
        txtResponsavel.setEnabled(false);
        txtCelular.setEnabled(false);
        cmbTipo.setEnabled(false);
        comboBoxUf.setEnabled(false);
    }

    private void habilitaCamposdeTexto() {

        txtCodUnidade.setEnabled(true);
        txtNomeUnidade.setEnabled(true);
        txtLogradouro.setEnabled(true);
        txtNumero.setEnabled(true);
        txtBairro.setEnabled(true);
        txtCidade.setEnabled(true);
        txtCep.setEnabled(true);
        txtFone1.setEnabled(true);
        txtFone2.setEnabled(true);
        txtResponsavel.setEnabled(true);
        txtCelular.setEnabled(true);
        cmbTipo.setEnabled(true);
        comboBoxUf.setEnabled(true);
    }

    private void LimpaCamposTexto() {

        txtCodUnidade.setText("");
        txtNomeUnidade.setText("");
        txtLogradouro.setText("");
        txtNumero.setText("");
        txtCidade.setText("");
        txtCep.setText("");
        txtFone1.setText("");
        txtFone2.setText("");
        txtResponsavel.setText("");
        txtCelular.setText("");

    }

    private void desmarcarRbButtons() {

        //jRadioButtonCodigo.setSelected(false);
        //jRadioButtonNome.setSelected(false);
        //jRadioButtonContato.setSelected(false);
        
        rbNovo.setSelected(false);
        rbExcluir.setSelected(false);
        rbAlterar.setSelected(false);
        
    }

    private void habilitaRbButtons() {
        rbNovo.setEnabled(true);
        rbExcluir.setEnabled(true);
        rbAlterar.setEnabled(true);

    }

}
