/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ConnectionDB;
import controller.ControllerRim;
import controller.ModelTabela;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import model.ModelRim;

/**
 *
 * @author Marco Antonio
 */
public class JFrameRim extends javax.swing.JFrame {

    /**
     * Creates new form JFrameRim
     */
    ConnectionDB conecta = new ConnectionDB();
    ConnectionDB conectaUnidade = new ConnectionDB();
    ModelRim requi = new ModelRim();// foi tornado global para não ter que instanciar novamente
    ControllerRim ri = new ControllerRim();
    int flag = 0;

    public JFrameRim() {
        initComponents();

        txtFlag.setVisible(false);
        txtDataCetilSQL.setVisible(false);

        desabilitaCamposdeTexto();
        conecta.conexao();
        preencherTabela("select * from rim order by Cod_rim");
        LimpaCamposTexto();
        populaCxCombinacaoUnidade();
        populaCxCombinacaoCadastrante();
        rbRim.setSelected(true);

        Date data = new Date(System.currentTimeMillis());
        SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy");
        txtDataCadastro.setText(formatador.format(data));

        Date anoprocessocontabil = new Date(System.currentTimeMillis());
        SimpleDateFormat formatador1 = new SimpleDateFormat("yyyy");
        txtAnoProcesso.setText(formatador1.format(anoprocessocontabil));

        Date anoprocesso = new Date(System.currentTimeMillis());
        SimpleDateFormat formatador2 = new SimpleDateFormat("yyyy");
        txtAnoProcessoContabil.setText(formatador2.format(anoprocesso));

        lblComprasPrim.setText("");
        lblContabilidade.setText("");
        lblOrdenadorAss.setText("");
        lblOrdenadorEmpenho.setText("");
        lblComprasSeg.setText("");
        lblDipe.setText("");

    }

    private void populaCxCombinacaoCadastrante() {

        try {
            cmbCadastrante.removeAllItems();
            conecta.executaSQL("Select * from usuario order by Cod_usuario");
            while (conecta.rs.next()) {
                cmbCadastrante.addItem(conecta.rs.getString("Login_usuario"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível popular o item.");
        }
    }

    private void populaCxCombinacaoUnidade() {

        try {
            cmbUnidade.removeAllItems();
            conecta.executaSQL("Select * from unidade order by Cod_unidade");

            while (conecta.rs.next()) {
                cmbUnidade.addItem(conecta.rs.getString("Nome_unidade"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível popular o item.");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtAnoPesquisa = new javax.swing.JTextField();
        txtCodigoPesquisa = new javax.swing.JTextField();
        txtUnidadePesquisa = new javax.swing.JTextField();
        txtCetilPesquisa = new javax.swing.JTextField();
        txtDataCetilPesquisa = new javax.swing.JTextField();
        txtProcessoPesquisa = new javax.swing.JTextField();
        txtProcessoContabilPesquisa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblPesquisa = new javax.swing.JLabel();
        txtDescricaoPesquisa = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        rbNovo = new javax.swing.JRadioButton();
        rbAlterar = new javax.swing.JRadioButton();
        rbExcluir = new javax.swing.JRadioButton();
        buttonOK = new javax.swing.JButton();
        buttonAlterar = new javax.swing.JButton();
        buttonExcluir = new javax.swing.JButton();
        buttonCancelar = new javax.swing.JButton();
        buttonSair = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtCetil = new javax.swing.JTextField();
        txtDataCetil = new javax.swing.JTextField();
        cmbUnidade = new javax.swing.JComboBox();
        txtProcesso = new javax.swing.JTextField();
        txtValorReal = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        txtDO = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        rbContabilidade = new javax.swing.JCheckBox();
        rbOrdenadorRi = new javax.swing.JCheckBox();
        rbComprasPrim = new javax.swing.JCheckBox();
        rbOrdenadorEmpenho = new javax.swing.JCheckBox();
        rbComprasSeg = new javax.swing.JCheckBox();
        rbDipe = new javax.swing.JCheckBox();
        lblContabilidade = new javax.swing.JLabel();
        lblOrdenadorAss = new javax.swing.JLabel();
        lblComprasPrim = new javax.swing.JLabel();
        lblOrdenadorEmpenho = new javax.swing.JLabel();
        lblComprasSeg = new javax.swing.JLabel();
        lblDipe = new javax.swing.JLabel();
        txtDataCadastro = new javax.swing.JTextField();
        cmbCadastrante = new javax.swing.JComboBox();
        jpAnotacoes = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAnotacoes = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtValorEstimado = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        txtAnoProcesso = new javax.swing.JTextField();
        buttonDespesas = new javax.swing.JButton();
        buttonEmpenho = new javax.swing.JButton();
        lblCodigo = new javax.swing.JLabel();
        rbRim = new javax.swing.JRadioButton();
        rbRrp = new javax.swing.JRadioButton();
        lblCadastro = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtProcessoContabil = new javax.swing.JTextField();
        txtAnoProcessoContabil = new javax.swing.JTextField();
        lblCodigoDespesa = new javax.swing.JLabel();
        lblCodigoUsuario = new javax.swing.JLabel();
        lblCodigoUnidade = new javax.swing.JLabel();
        txtDataCetilSQL = new javax.swing.JTextField();
        txtFlag = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableRim = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jCalendar = new com.toedter.calendar.JCalendar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("REQUISIÇÕES - Pesquisas e Movimentaçôes");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtAnoPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnoPesquisaActionPerformed(evt);
            }
        });
        txtAnoPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAnoPesquisaKeyPressed(evt);
            }
        });

        txtCodigoPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoPesquisaKeyPressed(evt);
            }
        });

        txtUnidadePesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUnidadePesquisaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUnidadePesquisaKeyReleased(evt);
            }
        });

        txtCetilPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCetilPesquisaKeyPressed(evt);
            }
        });

        txtProcessoPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtProcessoPesquisaKeyPressed(evt);
            }
        });

        txtProcessoContabilPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtProcessoContabilPesquisaKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setText("Ano");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("Código ");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setText("Descrição");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setText("Unidade Solicitante");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel5.setText("Proc. Contábil");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel6.setText("Cetil");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel7.setText("Data Cetil");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel8.setText("Processo");

        lblPesquisa.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblPesquisa.setText("Pesquisa");

        txtDescricaoPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDescricaoPesquisaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAnoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtCodigoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4)
                    .addComponent(txtUnidadePesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCetilPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtDataCetilPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(txtProcessoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(txtProcessoContabilPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel3)
                    .addComponent(txtDescricaoPesquisa))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(248, 248, 248))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(lblPesquisa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(5, 5, 5)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtAnoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCodigoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDescricaoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(24, 24, 24)))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUnidadePesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtCetilPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDataCetilPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(6, 6, 6)
                        .addComponent(txtProcessoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(6, 6, 6)
                        .addComponent(txtProcessoContabilPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        rbNovo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        rbNovo.setText("Novo");
        rbNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbNovoMouseClicked(evt);
            }
        });
        rbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNovoActionPerformed(evt);
            }
        });

        rbAlterar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        rbAlterar.setText("Alterar");
        rbAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbAlterarMouseClicked(evt);
            }
        });
        rbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAlterarActionPerformed(evt);
            }
        });

        rbExcluir.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        rbExcluir.setText("Excluir");
        rbExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbExcluirMouseClicked(evt);
            }
        });
        rbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbExcluirActionPerformed(evt);
            }
        });

        buttonOK.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        buttonOK.setText("OK");
        buttonOK.setEnabled(false);
        buttonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOKActionPerformed(evt);
            }
        });

        buttonAlterar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        buttonAlterar.setText("Alterar");
        buttonAlterar.setEnabled(false);
        buttonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAlterarActionPerformed(evt);
            }
        });

        buttonExcluir.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        buttonExcluir.setText("Excluir");
        buttonExcluir.setEnabled(false);
        buttonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluirActionPerformed(evt);
            }
        });

        buttonCancelar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        buttonCancelar.setText("Cancelar");
        buttonCancelar.setEnabled(false);
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });

        buttonSair.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        buttonSair.setText("Sair");
        buttonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbExcluir)
                    .addComponent(rbNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(buttonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(buttonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(rbNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(rbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(rbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonOK)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(buttonExcluir))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(buttonAlterar)))
                        .addGap(18, 18, 18)
                        .addComponent(buttonCancelar)
                        .addGap(8, 8, 8)
                        .addComponent(buttonSair)
                        .addGap(21, 21, 21))))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCetil.setText("9999");
        jPanel3.add(txtCetil, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 35, 55, 25));

        txtDataCetil.setText("02/07/2016");
        txtDataCetil.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDataCetilFocusGained(evt);
            }
        });
        txtDataCetil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataCetilActionPerformed(evt);
            }
        });
        jPanel3.add(txtDataCetil, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 35, 70, 25));

        cmbUnidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbUnidadeMouseClicked(evt);
            }
        });
        cmbUnidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUnidadeActionPerformed(evt);
            }
        });
        jPanel3.add(cmbUnidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 36, 250, 22));
        jPanel3.add(txtProcesso, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 203, 55, 25));

        txtValorReal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorRealActionPerformed(evt);
            }
        });
        jPanel3.add(txtValorReal, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 203, 88, 25));

        jTextField7.setText("R$");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 203, -1, 25));
        jPanel3.add(txtDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 203, 55, 25));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Trâmites", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14))); // NOI18N

        rbContabilidade.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        rbContabilidade.setText("1. Contabilidade");
        rbContabilidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rbContabilidadeFocusGained(evt);
            }
        });
        rbContabilidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbContabilidadeActionPerformed(evt);
            }
        });

        rbOrdenadorRi.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        rbOrdenadorRi.setText("2.Ordenador | R.I");
        rbOrdenadorRi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rbOrdenadorRiFocusGained(evt);
            }
        });
        rbOrdenadorRi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOrdenadorRiActionPerformed(evt);
            }
        });

        rbComprasPrim.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        rbComprasPrim.setText("3. Div.Compras | DCS");
        rbComprasPrim.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rbComprasPrimFocusGained(evt);
            }
        });
        rbComprasPrim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbComprasPrimActionPerformed(evt);
            }
        });

        rbOrdenadorEmpenho.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        rbOrdenadorEmpenho.setText("4. Ordenador | Empenho");
        rbOrdenadorEmpenho.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rbOrdenadorEmpenhoFocusGained(evt);
            }
        });
        rbOrdenadorEmpenho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOrdenadorEmpenhoActionPerformed(evt);
            }
        });

        rbComprasSeg.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        rbComprasSeg.setText("5. Div.Compras | DCS");
        rbComprasSeg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rbComprasSegFocusGained(evt);
            }
        });
        rbComprasSeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbComprasSegActionPerformed(evt);
            }
        });

        rbDipe.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        rbDipe.setText("6. Div. Planej.Econ.");
        rbDipe.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rbDipeFocusGained(evt);
            }
        });
        rbDipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDipeActionPerformed(evt);
            }
        });

        lblContabilidade.setText("jLabel14");

        lblOrdenadorAss.setText("jLabel15");

        lblComprasPrim.setText("jLabel16");

        lblOrdenadorEmpenho.setText("jLabel17");

        lblComprasSeg.setText("jLabel18");

        lblDipe.setText("jLabel19");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbContabilidade)
                    .addComponent(rbOrdenadorEmpenho)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblContabilidade)
                            .addComponent(lblOrdenadorEmpenho))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbOrdenadorRi)
                    .addComponent(rbComprasSeg)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblComprasSeg)
                            .addComponent(lblOrdenadorAss))))
                .addGap(48, 48, 48)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbComprasPrim)
                    .addComponent(rbDipe)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblComprasPrim)
                            .addComponent(lblDipe)))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(rbContabilidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblContabilidade))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbOrdenadorRi)
                            .addComponent(rbComprasPrim))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOrdenadorAss)
                            .addComponent(lblComprasPrim))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(rbOrdenadorEmpenho)
                        .addGap(3, 3, 3)
                        .addComponent(lblOrdenadorEmpenho))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbComprasSeg)
                            .addComponent(rbDipe))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblComprasSeg)
                            .addComponent(lblDipe))))
                .addGap(0, 0, 0))
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 259, 540, 130));

        txtDataCadastro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDataCadastroFocusGained(evt);
            }
        });
        txtDataCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataCadastroActionPerformed(evt);
            }
        });
        jPanel3.add(txtDataCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 422, 70, 25));

        jPanel3.add(cmbCadastrante, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 422, 207, 25));

        jpAnotacoes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Anotações", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14))); // NOI18N
        jpAnotacoes.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N

        txtAnotacoes.setColumns(20);
        txtAnotacoes.setRows(3);
        txtAnotacoes.setText(" \n\n\n\n");
        jScrollPane2.setViewportView(txtAnotacoes);

        javax.swing.GroupLayout jpAnotacoesLayout = new javax.swing.GroupLayout(jpAnotacoes);
        jpAnotacoes.setLayout(jpAnotacoesLayout);
        jpAnotacoesLayout.setHorizontalGroup(
            jpAnotacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAnotacoesLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jpAnotacoesLayout.setVerticalGroup(
            jpAnotacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAnotacoesLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel3.add(jpAnotacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 448, 540, 80));

        txtDescricao.setColumns(20);
        txtDescricao.setRows(4);
        jScrollPane1.setViewportView(txtDescricao);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 540, 70));

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel10.setText("Processo");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 184, -1, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel11.setText("Data Cetil *");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 14, -1, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel12.setText("Unidade Solicitante *");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 10, -1, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel13.setText("Descrição");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 81, -1, -1));

        jLabel21.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel21.setText("Cetil *");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 16, -1, -1));

        jLabel22.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel22.setText("D.O *");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 184, -1, -1));

        jLabel23.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel23.setText("Valor Real");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 184, 70, -1));

        jLabel24.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel24.setText("Valor Estimado *");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 184, 100, -1));
        jPanel3.add(txtValorEstimado, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 203, 88, 25));

        jLabel26.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel26.setText("Cadastrante *");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 401, -1, -1));

        jLabel27.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel27.setText("Data Cadastro");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 401, -1, -1));

        jTextField10.setText("R$");
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 203, -1, 25));
        jPanel3.add(txtAnoProcesso, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 203, 30, 25));

        buttonDespesas.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        buttonDespesas.setText("Despesas");
        jPanel3.add(buttonDespesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 234, -1, -1));

        buttonEmpenho.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        buttonEmpenho.setText("Empenho");
        jPanel3.add(buttonEmpenho, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 234, 90, -1));

        lblCodigo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 34, 50, 25));

        rbRim.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        rbRim.setForeground(new java.awt.Color(204, 0, 0));
        rbRim.setText("RIM");
        rbRim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRimActionPerformed(evt);
            }
        });
        jPanel3.add(rbRim, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 69, -1, -1));

        rbRrp.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        rbRrp.setForeground(new java.awt.Color(204, 0, 0));
        rbRrp.setText("RRP");
        rbRrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRrpActionPerformed(evt);
            }
        });
        jPanel3.add(rbRrp, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 69, -1, -1));

        lblCadastro.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblCadastro.setText("Cadastro");
        jPanel3.add(lblCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, 30));

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel14.setText("Processo Contábil");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 184, 110, -1));
        jPanel3.add(txtProcessoContabil, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 203, 70, 25));

        txtAnoProcessoContabil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnoProcessoContabilActionPerformed(evt);
            }
        });
        jPanel3.add(txtAnoProcessoContabil, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 203, 30, 25));

        lblCodigoDespesa.setText("6");
        lblCodigoDespesa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(lblCodigoDespesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        lblCodigoUsuario.setText("3");
        lblCodigoUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(lblCodigoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 400, -1, -1));

        lblCodigoUnidade.setText("5");
        lblCodigoUnidade.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(lblCodigoUnidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 9, -1, -1));
        jPanel3.add(txtDataCetilSQL, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 90, -1));

        txtFlag.setText("jTextField1");
        jPanel3.add(txtFlag, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTableRim.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableRim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableRimMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableRim);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1334, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jCalendar.setBackground(new java.awt.Color(204, 204, 204));
        jCalendar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCalendarMouseClicked(evt);
            }
        });
        jCalendar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jCalendarPropertyChange(evt);
            }
        });
        jCalendar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCalendarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rbNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbNovoMouseClicked
        // TODO add your handling code here:
        rbExcluir.setSelected(false);
        rbAlterar.setSelected(false);
        buttonOK.setEnabled(true);
        buttonCancelar.setEnabled(true);
        lblCadastro.setText("Cadastro");
        lblCadastro.setForeground(Color.red);
    }//GEN-LAST:event_rbNovoMouseClicked

    private void rbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNovoActionPerformed
        // TODO add your handling code here:
        desabilitaRbButtons();
        habilitaCamposdeTexto();

    }//GEN-LAST:event_rbNovoActionPerformed

    private void rbAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbAlterarMouseClicked
        // TODO add your handling code here:
        //desabilitaDemaisRbButtons();
        //rbExcluir.setSelected(false);
        //rbNovo.setSelected(false);
        buttonOK.setEnabled(true);
        buttonCancelar.setEnabled(true);
        lblCadastro.setText("Alterar");
        lblCadastro.setForeground(Color.red);
    }//GEN-LAST:event_rbAlterarMouseClicked

    private void rbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAlterarActionPerformed
        // TODO add your handling code here:
        desabilitaRbButtons();
        habilitaCamposdeTexto();
        lblCadastro.setText("Alterar");
        lblCadastro.setForeground(Color.red);
        buttonOK.setEnabled(true);
        buttonCancelar.setEnabled(true);

        JOptionPane.showMessageDialog(null, "Dê duplo clique com o mouse na linha da tabela acima\ncorrespondente à R.I que você quer alterar.");


    }//GEN-LAST:event_rbAlterarActionPerformed

    private void rbExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbExcluirMouseClicked
        // TODO add your handling code here:
        //desabilitaDemaisRbButtons();
        rbNovo.setSelected(false);
        rbAlterar.setSelected(false);
        buttonOK.setEnabled(true);
        buttonCancelar.setEnabled(true);
        lblCadastro.setText("Excluir");
        lblCadastro.setForeground(Color.red);
    }//GEN-LAST:event_rbExcluirMouseClicked

    private void rbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbExcluirActionPerformed
        // TODO add your handling code here:
        desabilitaRbButtons();
        buttonOK.setEnabled(true);
        buttonCancelar.setEnabled(true);
        lblCadastro.setText("Excluir");
        lblCadastro.setForeground(Color.red);
        JOptionPane.showMessageDialog(null, "Dê duplo clique com o mouse na linha da tabela acima\ncorrespondente à R.I que você quer excluir.");


    }//GEN-LAST:event_rbExcluirActionPerformed

    private void buttonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOKActionPerformed

        lblCadastro.setText("");
        lblCadastro.setForeground(Color.white);
        // foi tornado global para não ter que declarar novamente

        //rim.setCodRim(Integer.valueOf(txtCetil.getText()));
        requi.setUnidade(cmbUnidade.getSelectedItem().toString());
        requi.setDescricao(txtDescricao.getText());
        requi.setDotacao(txtDO.getText());
        if (rbRim.isSelected()) {
            requi.setTipoRim("RIM");
        } else {
            requi.setTipoRim("RRP");
        }
        requi.setCetil(txtCetil.getText());
        requi.setDataCetil(txtDataCetil.getText());
        //requi.setDataCetilSql(Date.valueOf(txtDataCetilSQL.getText()));
        requi.setValorEstimado(txtValorEstimado.getText());
        requi.setValorReal(txtValorReal.getText());
        requi.setProcesso(txtProcesso.getText());
        requi.setAnoProcesso(Integer.valueOf(txtAnoProcesso.getText()));
        requi.setProcessoContabil(txtProcessoContabil.getText());
        requi.setAnoProcessoContabil(Integer.valueOf(txtAnoProcessoContabil.getText()));
        requi.setContabilidade(lblContabilidade.getText());
        requi.setOrdenadorass(lblOrdenadorAss.getText());
        requi.setCompraprim(lblComprasPrim.getText());
        requi.setOrdenadorEmpenho(lblOrdenadorEmpenho.getText());
        requi.setComprasSeg(lblComprasSeg.getText());
        requi.setDipe(lblDipe.getText());
        requi.setCadastrante(cmbCadastrante.getName());
        requi.setDataCadastro(txtDataCadastro.getText());
        requi.setObservacao(txtAnotacoes.getText());
        requi.setCodUsuario(Integer.valueOf(lblCodigoUsuario.getText()));
        requi.setCodUnidade(Integer.valueOf(lblCodigoDespesa.getText()));

        // Condição que controla qual método vai ser utilizado dependendo do radio button selecionado.
        if (rbNovo.isSelected()) {
            //JOptionPane.showMessageDialog(null, "Chama o método de inserção da RIM");
            try {
                ri.InserirRequisicao(requi);
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(null, "Erro! Motivo/n" + ex);
            }
        } else if (rbExcluir.isSelected()) {
            if (!"".equals(lblCodigo.getText())) {
                requi.setCodRim(Integer.valueOf(lblCodigo.getText()));
                ri.ExcluirRequisicao(requi);
            } else {
                JOptionPane.showMessageDialog(null, "Escolha na tabela o item a ser excluído.");
            }
        } else {
            if (!"".equals(lblCodigo.getText())) {
                requi.setCodRim(Integer.valueOf(lblCodigo.getText()));
                ri.AlterarRequisicao(requi);
            } else {
                JOptionPane.showMessageDialog(null, "Escolha na tabela o item a ser alterado.");
            }
        }
    }//GEN-LAST:event_buttonOKActionPerformed

    private void buttonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAlterarActionPerformed
        // TODO add your handling code here:
        requi.setCodRim(Integer.valueOf(lblCodigo.getText()));

        ri.AlterarRequisicao(requi);
    }//GEN-LAST:event_buttonAlterarActionPerformed

    private void buttonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExcluirActionPerformed

        /* BOTÃO DESATIVADO...
         //despesa.setCodDespesa(Integer.valueOf(txtCodigo.getText()));
         //ControllerDespesa des = new ControllerDespesa();
         despesa.setCodDespesa(Integer.valueOf(txtCodigoPesquisa.getText()));
         despesa.setDespesa(txtDespesa.getText());
         despesa.setReduzida(txtReduzida.getText());
         despesa.setPrograma(txtPrograma.getText());
         despesa.setAplicacao(txtAplicacao.getText());

         des.ExcluirDespesa(despesa);
         */
    }//GEN-LAST:event_buttonExcluirActionPerformed

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
        // TODO add your handling code here:
        habilitaRbButtons();
        LimpaCamposTexto();
        //desabilitaCamposdeTexto();
        desmarcarRbButtons();
        lblCadastro.setText("");
        lblCadastro.setForeground(Color.white);
        buttonOK.setEnabled(false);
    }//GEN-LAST:event_buttonCancelarActionPerformed

    private void desmarcarRbButtons() {

        rbNovo.setSelected(false);
        rbExcluir.setSelected(false);
        rbAlterar.setSelected(false);
    }

    private void desabilitaRbButtons() {

        rbNovo.setEnabled(false);
        rbExcluir.setEnabled(false);
        rbAlterar.setEnabled(false);

    }

    private void habilitaRbButtons() {
        rbNovo.setEnabled(true);
        rbExcluir.setEnabled(true);
        rbAlterar.setEnabled(true);
    }


    private void buttonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_buttonSairActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void txtValorRealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorRealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorRealActionPerformed

    private void txtDataCetilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataCetilActionPerformed
        // TODO add your handling code here:

        flag = 1;
        txtFlag.setText(String.valueOf(flag));

        String dataCetil = txtDataCetil.getText();
        /*
         SimpleDateFormat stf = new SimpleDateFormat("dd/MM/yyyy");
         try {
         java.util.Date d = stf.parse("yyyy-MM-dd");
         txtDataCetilSQL.setText("" + d);
         } catch (ParseException ex) {
         Logger.getLogger(JFrameRim.class.getName()).log(Level.SEVERE, null, ex);
         }
         */

    }//GEN-LAST:event_txtDataCetilActionPerformed

    private void rbComprasSegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbComprasSegActionPerformed
        // TODO add your handling code here:
        flag = 6;
        txtFlag.setText(String.valueOf(flag));
    }//GEN-LAST:event_rbComprasSegActionPerformed

    private void rbDipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDipeActionPerformed
        // TODO add your handling code here:
        flag = 7;
        txtFlag.setText(String.valueOf(flag));
    }//GEN-LAST:event_rbDipeActionPerformed

    private void jTableRimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableRimMouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            //Preenche os Campos de Texto correspondentes ao clicar numa linha do JTable
            String codigodarim = "" + jTableRim.getValueAt(jTableRim.getSelectedRow(), 0);
            conecta.conexao();
            conecta.executaSQL("Select * from rim where cod_rim='" + codigodarim + "'");
            conecta.rs.first();
            lblCodigo.setText(String.valueOf(conecta.rs.getInt("Cod_rim")));
            //cmbUnidade.setName(String.valueOf(conecta.rs.getString("Nome_Unidade")));

            txtDescricao.setText(String.valueOf(conecta.rs.getString("Descricao")));
            txtDO.setText(String.valueOf(conecta.rs.getString("Dotacao")));
            //conecta.rs.getString("Tipo_RIM")));
            txtCetil.setText(String.valueOf(conecta.rs.getString("Cetil")));
            txtDataCetil.setText(String.valueOf(conecta.rs.getString("DataCetil")));
            //conecta.rs.getString("DataCetilSQL")
            txtValorEstimado.setText(String.valueOf(conecta.rs.getString("ValorEstimado")));
            txtValorReal.setText(String.valueOf(conecta.rs.getString("ValorReal")));
            txtProcesso.setText(String.valueOf(conecta.rs.getString("Processo")));
            txtAnoProcesso.setText(String.valueOf(conecta.rs.getInt("ano_processo")));
            txtProcessoContabil.setText(String.valueOf(conecta.rs.getString("ProcessoContabil")));
            txtAnoProcessoContabil.setText(String.valueOf(conecta.rs.getInt("ano_processo_contabil")));
            lblContabilidade.setText(String.valueOf(conecta.rs.getString("Contabilidade")));
            lblOrdenadorAss.setText(String.valueOf(conecta.rs.getString("OrdenadorAss")));
            lblComprasPrim.setText(String.valueOf(conecta.rs.getString("ComprasPrim")));
            lblOrdenadorEmpenho.setText(String.valueOf(conecta.rs.getString("OrdenadorEmpenho")));
            lblComprasSeg.setText(String.valueOf(conecta.rs.getString("ComprasSeg")));
            lblDipe.setText(String.valueOf(conecta.rs.getString("Dipe")));
            //cmbCadastrante.setName(String.valueOf(conecta.rs.getString("Cadastrante")));
            txtDataCadastro.setText(String.valueOf(conecta.rs.getString("DataCadastro")));
            txtAnotacoes.setText(String.valueOf(conecta.rs.getString("Observacao")));
            // conecta.rs.getString("Atendida")
            // conecta.rs.getString("Concluida")
            lblCodigoUsuario.setText(String.valueOf(conecta.rs.getInt("Cd_usuario")));
            lblCodigoDespesa.setText(String.valueOf(conecta.rs.getInt("Cd_unidade")));
            //conecta.desconectar();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao capturar dados da linha selecionada\n [ " + ex + "] ");
        }

    }//GEN-LAST:event_jTableRimMouseClicked

    private void txtAnoProcessoContabilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnoProcessoContabilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnoProcessoContabilActionPerformed

    private void cmbUnidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbUnidadeMouseClicked

        // setando no lblUnidade o código correspondente ao da unidade selecionada em  cmbUnidade
        //String unidadeSelecionada = (String) cmbUnidade.getSelectedItem();
        //txtDataCetilSQL.setText("" + unidadeSelecionada);

    }//GEN-LAST:event_cmbUnidadeMouseClicked

    private void cmbUnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUnidadeActionPerformed

        /*
         try {
         conectaUnidade.executaSQL("Select Cod_unidade from unidade where nome_unidade='" + txtDataCetilSQL.getText() + "'");
         lblCodigoUnidade.setText(conectaUnidade.rs.getString("Cod_unidade"));
         } catch (SQLException ex) {
         Logger.getLogger(JFrameRim.class.getName()).log(Level.SEVERE, null, ex);
         }
         */
        // TODO add your handling code here:
        //String unidadeSelecionada = (String) cmbUnidade.getSelectedItem();
        txtDataCetilSQL.setText("" + (String) cmbUnidade.getSelectedItem());

        /*
         conecta.conexao();// abre a conexão
         conecta.executaSQL("Select cod_Unidade from unidade where Nome_unidade='" + unidadeSelecionada + "'");

         try {
         //conecta.executaSQL("Select cod_Unidade from unidade where Nome_unidade='" + unidadeSelecionada + "'");
         lblCodigoUnidade.setText(conecta.rs.getString("Cod_Unidade"));
         } catch (SQLException ex) {
         Logger.getLogger(JFrameRim.class.getName()).log(Level.SEVERE, null, ex);
         }
         */

    }//GEN-LAST:event_cmbUnidadeActionPerformed

    private void jCalendarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCalendarKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jCalendarKeyPressed

    private void jCalendarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCalendarMouseClicked

    // TODO add your handling code here:

    }//GEN-LAST:event_jCalendarMouseClicked

    private void jCalendarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jCalendarPropertyChange
        // TODO add your handling code here:
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy"); //DEFINE FORMATO DE DATA
        String data = formato.format(jCalendar.getDate()); //CONVERTE PRA STRING
        //JOptionPane.showMessageDialog(null, data); //EXIBE O CALENDARIO QUANDO CARREGADO E A CADA TROCA DE DATA, MÊS OU ANO
     /*AGORA TROCANDO ESSE JOptionPane ACIMA, VC PODE COLOCAR O JTextFeld COMO NO EXEMPLO ABAIXO: */

        switch (flag) {
            case 1:
                txtDataCetil.setText(data);
                break;
            case 2:
                lblContabilidade.setText(data);
                break;
            case 3:
                lblOrdenadorAss.setText(data);
                break;
            case 4:
                lblComprasPrim.setText(data);
                break;
            case 5:
                lblOrdenadorEmpenho.setText(data);
                break;
            case 6:
                lblComprasSeg.setText(data);
                break;
            case 7:
                lblDipe.setText(data);
                break;
            case 8:
                txtDataCadastro.setText(data);
                break;
        }

    }//GEN-LAST:event_jCalendarPropertyChange

    private void rbContabilidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbContabilidadeActionPerformed
        // TODO add your handling code here:
        flag = 2;
        txtFlag.setText(String.valueOf(flag));
    }//GEN-LAST:event_rbContabilidadeActionPerformed

    private void rbOrdenadorRiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOrdenadorRiActionPerformed
        // TODO add your handling code here:
        flag = 3;
        txtFlag.setText(String.valueOf(flag));
    }//GEN-LAST:event_rbOrdenadorRiActionPerformed

    private void rbComprasPrimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbComprasPrimActionPerformed
        // TODO add your handling code here:
        flag = 4;
        txtFlag.setText(String.valueOf(flag));
    }//GEN-LAST:event_rbComprasPrimActionPerformed

    private void rbOrdenadorEmpenhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOrdenadorEmpenhoActionPerformed
        // TODO add your handling code here:
        flag = 5;
        txtFlag.setText(String.valueOf(flag));
    }//GEN-LAST:event_rbOrdenadorEmpenhoActionPerformed

    private void txtDataCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataCadastroActionPerformed
        // TODO add your handling code here:
        flag = 8;
        txtFlag.setText(String.valueOf(flag));
    }//GEN-LAST:event_txtDataCadastroActionPerformed

    private void txtDataCetilFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDataCetilFocusGained
        // TODO add your handling code here:
        flag = 1;
        txtFlag.setText(String.valueOf(flag));
    }//GEN-LAST:event_txtDataCetilFocusGained

    private void txtDataCadastroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDataCadastroFocusGained
        // TODO add your handling code here:
        flag = 8;
        txtFlag.setText(String.valueOf(flag));
    }//GEN-LAST:event_txtDataCadastroFocusGained

    private void rbContabilidadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rbContabilidadeFocusGained
        // TODO add your handling code here:
        flag = 2;
        txtFlag.setText(String.valueOf(flag));
    }//GEN-LAST:event_rbContabilidadeFocusGained

    private void rbOrdenadorRiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rbOrdenadorRiFocusGained
        // TODO add your handling code here:
        flag = 3;
        txtFlag.setText(String.valueOf(flag));
    }//GEN-LAST:event_rbOrdenadorRiFocusGained

    private void rbComprasPrimFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rbComprasPrimFocusGained
        // TODO add your handling code here:
        flag = 4;
        txtFlag.setText(String.valueOf(flag));
    }//GEN-LAST:event_rbComprasPrimFocusGained

    private void rbOrdenadorEmpenhoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rbOrdenadorEmpenhoFocusGained
        // TODO add your handling code here:
        flag = 5;
        txtFlag.setText(String.valueOf(flag));
    }//GEN-LAST:event_rbOrdenadorEmpenhoFocusGained

    private void rbComprasSegFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rbComprasSegFocusGained
        // TODO add your handling code here:
        flag = 6;
        txtFlag.setText(String.valueOf(flag));
    }//GEN-LAST:event_rbComprasSegFocusGained

    private void rbDipeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rbDipeFocusGained
        // TODO add your handling code here:
        flag = 7;
        txtFlag.setText(String.valueOf(flag));
    }//GEN-LAST:event_rbDipeFocusGained

    private void rbRimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRimActionPerformed

        if (rbRim.isSelected()) {
            rbRrp.setSelected(false);
        } else {
            rbRrp.setSelected(true);
        }
    }//GEN-LAST:event_rbRimActionPerformed

    private void rbRrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRrpActionPerformed
        if (rbRrp.isSelected()) {
            rbRim.setSelected(false);
        } else {
            rbRim.setSelected(true);
        }
    }//GEN-LAST:event_rbRrpActionPerformed

    private void txtAnoPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnoPesquisaKeyPressed

        //preencherTabela("Select * From rim order by cod_rim");
        String pesquisadatarim = txtAnoPesquisa.getText();

        if (pesquisadatarim.length() > 0) {
            for (int i = 0; i < jTableRim.getRowCount(); i++) {
                if (!pesquisadatarim.equals(jTableRim.getValueAt(i, 1).toString())) {

                    // preencherTabela("Select * From dotacao where despesa=''");
                } else {
                    //JOptionPane.showMessageDialog(null,jTableDespesa.getValueAt(i, 0).toString() );
                    //txtCodigo.setText(jTableDespesa.getValueAt(i, 0).toString());
                    //txtDespesa.setText(jTableDespesa.getValueAt(i, 1).toString());
                    //txtReduzida.setText(jTableDespesa.getValueAt(i, 2).toString());
                    //txtPrograma.setText(jTableDespesa.getValueAt(i, 3).toString());
                    //txtAplicacao.setText(jTableDespesa.getValueAt(i, 4).toString());
                    preencherTabela("Select * From rim where DataCetil='" + pesquisadatarim + "'");
                }
            }
        }


    }//GEN-LAST:event_txtAnoPesquisaKeyPressed

    private void txtAnoPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnoPesquisaActionPerformed


    }//GEN-LAST:event_txtAnoPesquisaActionPerformed

    private void txtCodigoPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoPesquisaKeyPressed

        preencherTabela("Select * from rim order by cod_rim");
        habilitaCamposdeTexto();
        String pesquisaporcodigorim = txtCodigoPesquisa.getText();

        if (pesquisaporcodigorim.length() > 0) {
            for (int i = 0; i < jTableRim.getRowCount(); i++) {
                if (!pesquisaporcodigorim.equals(jTableRim.getValueAt(i, 0).toString())) {
                } else {
                    preencherTabela("Select * From rim where Cod_rim='" + pesquisaporcodigorim + "'");
                }
            }
        }
    }//GEN-LAST:event_txtCodigoPesquisaKeyPressed

    private void txtDescricaoPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescricaoPesquisaKeyPressed

        //txtDescricaoPesquisa.setText(txtDescricaoPesquisa.getText().toUpperCase());
                    
       // if (evt.getKeyCode() == evt.VK_ENTER) {
            preencherTabela("Select * from rim order by cod_rim");
            //habilitaCamposdeTexto();
            String pesquisadescricao = txtDescricaoPesquisa.getText().toUpperCase();
            if (pesquisadescricao.length() > 0) {
                for (int i = 0; i < jTableRim.getRowCount(); i++) {
                    if (!pesquisadescricao.equals(jTableRim.getValueAt(i, 2).toString())) {
                    } else {
                        preencherTabela("Select * From rim where descricao like '%" + pesquisadescricao + "%'");
                    }
                }
            }
        //}
    }//GEN-LAST:event_txtDescricaoPesquisaKeyPressed

    private void txtCetilPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCetilPesquisaKeyPressed

        preencherTabela("Select * from rim order by cod_rim");
        habilitaCamposdeTexto();
        String pesquisaporetil = txtCetilPesquisa.getText();

        if (pesquisaporetil.length() > 0) {
            for (int i = 0; i < jTableRim.getRowCount(); i++) {
                if (!pesquisaporetil.equals(jTableRim.getValueAt(i, 5).toString())) {
                } else {
                    preencherTabela("Select * From rim where cetil='" + pesquisaporetil + "'");
                }
            }
        }
    }//GEN-LAST:event_txtCetilPesquisaKeyPressed

    private void txtProcessoPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProcessoPesquisaKeyPressed

        // TODO add your handling code here:
        preencherTabela("Select * from rim order by cod_rim");
        habilitaCamposdeTexto();
        String pesquisaporcodigoprocesso = txtProcessoPesquisa.getText();

        if (pesquisaporcodigoprocesso.length() > 0) {
            for (int i = 0; i < jTableRim.getRowCount(); i++) {
                if (!pesquisaporcodigoprocesso.equals(jTableRim.getValueAt(i, 10).toString())) {
                } else {
                    preencherTabela("Select * From rim where Processo='" + pesquisaporcodigoprocesso + "'");
                }
            }
        }
    }//GEN-LAST:event_txtProcessoPesquisaKeyPressed

    private void txtProcessoContabilPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProcessoContabilPesquisaKeyPressed

// TODO add your handling code here:
        preencherTabela("Select * from rim order by cod_rim");
        habilitaCamposdeTexto();
        String pesquisaporcodigoprocessocontabil = txtProcessoContabilPesquisa.getText();

        if (pesquisaporcodigoprocessocontabil.length() > 0) {
            for (int i = 0; i < jTableRim.getRowCount(); i++) {
                if (!pesquisaporcodigoprocessocontabil.equals(jTableRim.getValueAt(i, 12).toString())) {
                } else {
                    preencherTabela("Select * From rim where ProcessoContabil='" + pesquisaporcodigoprocessocontabil + "'");
                }
            }
        }
    }//GEN-LAST:event_txtProcessoContabilPesquisaKeyPressed

    private void txtUnidadePesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUnidadePesquisaKeyPressed
        
        preencherTabela("Select * from rim order by cod_rim");
        habilitaCamposdeTexto();
        String pesquisaporunidade = txtUnidadePesquisa.getText().toUpperCase();

        if (pesquisaporunidade.length() > 0) {
            for (int i = 0; i < jTableRim.getRowCount(); i++) {
                if (!pesquisaporunidade.equals(jTableRim.getValueAt(i, 1).toString())) {
                } else {
                    preencherTabela("Select * From rim where Nome_Unidade LIKE '%" + pesquisaporunidade +"%'");
                }
            }
        }
    }//GEN-LAST:event_txtUnidadePesquisaKeyPressed

    private void txtUnidadePesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUnidadePesquisaKeyReleased
        
    }//GEN-LAST:event_txtUnidadePesquisaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameRim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameRim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameRim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameRim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameRim().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAlterar;
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JButton buttonDespesas;
    private javax.swing.JButton buttonEmpenho;
    private javax.swing.JButton buttonExcluir;
    private javax.swing.JButton buttonOK;
    private javax.swing.JButton buttonSair;
    private javax.swing.JComboBox cmbCadastrante;
    private javax.swing.JComboBox cmbUnidade;
    private com.toedter.calendar.JCalendar jCalendar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableRim;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JPanel jpAnotacoes;
    private javax.swing.JLabel lblCadastro;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCodigoDespesa;
    private javax.swing.JLabel lblCodigoUnidade;
    private javax.swing.JLabel lblCodigoUsuario;
    private javax.swing.JLabel lblComprasPrim;
    private javax.swing.JLabel lblComprasSeg;
    private javax.swing.JLabel lblContabilidade;
    private javax.swing.JLabel lblDipe;
    private javax.swing.JLabel lblOrdenadorAss;
    private javax.swing.JLabel lblOrdenadorEmpenho;
    private javax.swing.JLabel lblPesquisa;
    private javax.swing.JRadioButton rbAlterar;
    private javax.swing.JCheckBox rbComprasPrim;
    private javax.swing.JCheckBox rbComprasSeg;
    private javax.swing.JCheckBox rbContabilidade;
    private javax.swing.JCheckBox rbDipe;
    private javax.swing.JRadioButton rbExcluir;
    private javax.swing.JRadioButton rbNovo;
    private javax.swing.JCheckBox rbOrdenadorEmpenho;
    private javax.swing.JCheckBox rbOrdenadorRi;
    private javax.swing.JRadioButton rbRim;
    private javax.swing.JRadioButton rbRrp;
    private javax.swing.JTextField txtAnoPesquisa;
    private javax.swing.JTextField txtAnoProcesso;
    private javax.swing.JTextField txtAnoProcessoContabil;
    private javax.swing.JTextArea txtAnotacoes;
    private javax.swing.JTextField txtCetil;
    private javax.swing.JTextField txtCetilPesquisa;
    private javax.swing.JTextField txtCodigoPesquisa;
    private javax.swing.JTextField txtDO;
    private javax.swing.JTextField txtDataCadastro;
    private javax.swing.JTextField txtDataCetil;
    private javax.swing.JTextField txtDataCetilPesquisa;
    private javax.swing.JTextField txtDataCetilSQL;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JTextField txtDescricaoPesquisa;
    private javax.swing.JTextField txtFlag;
    private javax.swing.JTextField txtProcesso;
    private javax.swing.JTextField txtProcessoContabil;
    private javax.swing.JTextField txtProcessoContabilPesquisa;
    private javax.swing.JTextField txtProcessoPesquisa;
    private javax.swing.JTextField txtUnidadePesquisa;
    private javax.swing.JTextField txtValorEstimado;
    private javax.swing.JTextField txtValorReal;
    // End of variables declaration//GEN-END:variables

    private void LimpaCamposTexto() {
        txtAnoPesquisa.setText("");
        txtCetilPesquisa.setText("");
        txtCodigoPesquisa.setText("");
        txtDataCetilPesquisa.setText("");
        txtDescricaoPesquisa.setText("");
        txtProcessoPesquisa.setText("");
        txtUnidadePesquisa.setText("");
        txtProcessoContabilPesquisa.setText("");
    }

    private void habilitaCamposdeTexto() {

        txtCetil.setEnabled(true);
        txtDataCetil.setEnabled(true);
        cmbUnidade.setEnabled(true);
        txtProcesso.setEnabled(true);
        txtAnoProcesso.setEnabled(true);
        txtDO.setEnabled(true);
        txtProcessoContabil.setEnabled(true);
        txtAnoProcessoContabil.setEnabled(true);
        txtDescricao.setEnabled(true);
        cmbCadastrante.setEnabled(true);
        txtDataCadastro.setEnabled(true);
        txtAnotacoes.setEnabled(true);
        txtValorEstimado.setEnabled(true);
        txtValorReal.setEnabled(true);

    }

    private void preencherTabela(String SQL) {

        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{
            "Cód.Seq",
            "Unidade",
            "Descrição",
            "Dotaçao",
            "Tipo",
            "Cetil",
            "Data",
            "DataSQL",
            "R$-Estimado",
            "R$-Real",
            "Processo",
            "Ano",
            "Proc.Contábil",
            "Ano",
            "Contabilidade",
            "Ordenador",
            "Compras",
            "Ordenador",
            "Compras/DCS",
            "Dipe",
            "Cadastrante",
            "Data Cad.",
            "Obs.",
            "Atendida",
            "Concluída",
            "Usuário",
            "Unidade"};

        conecta.executaSQL(SQL);

        try {
            conecta.rs.first();
            do {
                dados.add(new Object[]{
                    conecta.rs.getInt("Cod_rim"),
                    conecta.rs.getString("Nome_Unidade"),
                    conecta.rs.getString("Descricao"),
                    conecta.rs.getString("Dotacao"),
                    conecta.rs.getString("Tipo_RIM"),
                    conecta.rs.getString("Cetil"),
                    conecta.rs.getString("DataCetil"),
                    conecta.rs.getString("DataCetilSQL"),// pega string ou a data?
                    conecta.rs.getString("ValorEstimado"),
                    conecta.rs.getString("ValorReal"),
                    conecta.rs.getString("Processo"),
                    conecta.rs.getInt("ano_processo"),
                    conecta.rs.getString("ProcessoContabil"),
                    conecta.rs.getInt("ano_processo_contabil"),
                    conecta.rs.getString("Contabilidade"),
                    conecta.rs.getString("OrdenadorAss"),
                    conecta.rs.getString("ComprasPrim"),
                    conecta.rs.getString("OrdenadorEmpenho"),
                    conecta.rs.getString("ComprasSeg"),
                    conecta.rs.getString("Dipe"),
                    conecta.rs.getString("Cadastrante"),
                    conecta.rs.getString("DataCadastro"),
                    conecta.rs.getString("Observacao"),
                    conecta.rs.getString("Atendida"),
                    conecta.rs.getString("Concluida"),
                    conecta.rs.getInt("Cd_usuario"),
                    conecta.rs.getInt("Cd_unidade"),});

            } while (conecta.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Informação não encontrada.\n" + ex.getMessage());
        }

        //Criando a Tabela
        ModelTabela modelo = new ModelTabela(dados, colunas);
        jTableRim.setModel(modelo);
        jTableRim.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTableRim.getColumnModel().getColumn(0).setResizable(false);

        jTableRim.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTableRim.getColumnModel().getColumn(1).setResizable(false);

        jTableRim.getColumnModel().getColumn(2).setPreferredWidth(150);
        jTableRim.getColumnModel().getColumn(2).setResizable(true);

        jTableRim.getColumnModel().getColumn(3).setPreferredWidth(60);
        jTableRim.getColumnModel().getColumn(3).setResizable(false);

        jTableRim.getColumnModel().getColumn(4).setPreferredWidth(40);
        jTableRim.getColumnModel().getColumn(4).setResizable(false);

        jTableRim.getColumnModel().getColumn(5).setPreferredWidth(40);
        jTableRim.getColumnModel().getColumn(5).setResizable(false);

        jTableRim.getColumnModel().getColumn(6).setPreferredWidth(80);
        jTableRim.getColumnModel().getColumn(6).setResizable(false);

        jTableRim.getColumnModel().getColumn(7).setPreferredWidth(0);
        jTableRim.getColumnModel().getColumn(7).setResizable(false);

        jTableRim.getColumnModel().getColumn(8).setPreferredWidth(80);
        jTableRim.getColumnModel().getColumn(8).setResizable(false);

        jTableRim.getColumnModel().getColumn(9).setPreferredWidth(80);
        jTableRim.getColumnModel().getColumn(9).setResizable(false);

        jTableRim.getColumnModel().getColumn(10).setPreferredWidth(80);
        jTableRim.getColumnModel().getColumn(10).setResizable(false);

        jTableRim.getColumnModel().getColumn(11).setResizable(false);
        jTableRim.getColumnModel().getColumn(11).setPreferredWidth(80);

        jTableRim.getColumnModel().getColumn(12).setResizable(false);
        jTableRim.getColumnModel().getColumn(12).setPreferredWidth(80);

        jTableRim.getColumnModel().getColumn(13).setResizable(false);
        jTableRim.getColumnModel().getColumn(13).setPreferredWidth(80);

        jTableRim.getColumnModel().getColumn(14).setResizable(false);
        jTableRim.getColumnModel().getColumn(14).setPreferredWidth(60);

        jTableRim.getColumnModel().getColumn(15).setResizable(false);
        jTableRim.getColumnModel().getColumn(15).setPreferredWidth(60);

        jTableRim.getColumnModel().getColumn(16).setResizable(false);
        jTableRim.getColumnModel().getColumn(16).setPreferredWidth(60);

        jTableRim.getColumnModel().getColumn(17).setResizable(false);
        jTableRim.getColumnModel().getColumn(17).setPreferredWidth(40);

        jTableRim.getColumnModel().getColumn(18).setResizable(false);
        jTableRim.getColumnModel().getColumn(18).setPreferredWidth(120);

        jTableRim.getColumnModel().getColumn(19).setResizable(false);
        jTableRim.getColumnModel().getColumn(19).setPreferredWidth(120);

        jTableRim.getColumnModel().getColumn(20).setResizable(false);
        jTableRim.getColumnModel().getColumn(20).setPreferredWidth(120);

        jTableRim.getColumnModel().getColumn(20).setPreferredWidth(120);
        jTableRim.getColumnModel().getColumn(21).setResizable(false);

        jTableRim.getColumnModel().getColumn(22).setPreferredWidth(120);
        jTableRim.getColumnModel().getColumn(22).setResizable(false);

        jTableRim.getColumnModel().getColumn(23).setPreferredWidth(120);
        jTableRim.getColumnModel().getColumn(23).setResizable(false);

        jTableRim.getColumnModel().getColumn(24).setPreferredWidth(120);
        jTableRim.getColumnModel().getColumn(24).setResizable(false);

        jTableRim.getColumnModel().getColumn(25).setPreferredWidth(120);
        jTableRim.getColumnModel().getColumn(25).setResizable(false);

        jTableRim.getColumnModel().getColumn(26).setPreferredWidth(120);
        jTableRim.getColumnModel().getColumn(26).setResizable(false);

        jTableRim.getTableHeader().setReorderingAllowed(false);
        jTableRim.setAutoResizeMode(jTableRim.AUTO_RESIZE_OFF);

        jTableRim.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }

    private void desabilitaCamposdeTexto() {

        txtCetil.setEnabled(false);
        txtDataCetil.setEnabled(false);
        cmbUnidade.setEnabled(false);
        txtProcesso.setEnabled(false);
        txtAnoProcesso.setEnabled(false);
        txtDO.setEnabled(false);
        txtProcessoContabil.setEnabled(false);
        txtAnoProcessoContabil.setEnabled(false);
        txtDescricao.setEnabled(false);
        cmbCadastrante.setEnabled(false);
        txtDataCadastro.setEnabled(false);
        txtAnotacoes.setEnabled(false);
        txtValorEstimado.setEnabled(false);
        txtValorReal.setEnabled(false);

    }

}
