/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ConnectionDB;
import controller.ControllerDespesa;
import controller.ModelTabela;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import model.ModelDespesa;

/**
 *
 * @author Marco Antonio
 */
public class JFrameDespesa extends javax.swing.JFrame {

    //ConnectionDB conexao = new ConnectionDB();
    //ControllerDespesa desp = new ControllerDespesa();
    ConnectionDB conecta = new ConnectionDB();
    ModelDespesa despesa = new ModelDespesa();// foi tornado global para não ter que instanciar novamente
    ControllerDespesa des = new ControllerDespesa();

// novamente no botão excluir.
    /**
     * Creates new form JFrameDespesa
     */
    public JFrameDespesa() {
        initComponents();
        // desabilitando os campos de texto para edição ao abrir o formulário
        desabilitaCamposdeTexto();
        conecta.conexao();
        preencherTabela("select * from dotacao order by Cod_Despesa");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panelPesquisa = new java.awt.Panel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDespesa = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        txtCodigo = new java.awt.TextField();
        label2 = new java.awt.Label();
        txtDespesa = new java.awt.TextField();
        label3 = new java.awt.Label();
        txtReduzida = new java.awt.TextField();
        label4 = new java.awt.Label();
        txtPrograma = new java.awt.TextField();
        label5 = new java.awt.Label();
        txtAplicacao = new java.awt.TextField();
        rbNovo = new javax.swing.JRadioButton();
        rbAlterar = new javax.swing.JRadioButton();
        rbExcluir = new javax.swing.JRadioButton();
        buttonOK = new javax.swing.JButton();
        buttonCancelar = new javax.swing.JButton();
        buttonSair = new javax.swing.JButton();
        buttonExcluir = new javax.swing.JButton();
        buttonAlterar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        label6 = new java.awt.Label();
        txtCodigoPesquisa = new java.awt.TextField();
        label7 = new java.awt.Label();
        txtDespesaPesquisa = new java.awt.TextField();
        label8 = new java.awt.Label();
        txtReduzidaPesquisa = new java.awt.TextField();
        label9 = new java.awt.Label();
        txtProgramaPesquisa = new java.awt.TextField();
        label10 = new java.awt.Label();
        txtAplicacaoPesquisa = new java.awt.TextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Despesas");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableDespesa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableDespesa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDespesaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableDespesa);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label1.setText("Código");
        jPanel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 15));

        txtCodigo.setEnabled(false);
        jPanel1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 72, -1));

        label2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label2.setText("Desdobrada");
        jPanel1.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 15));

        txtDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDespesaActionPerformed(evt);
            }
        });
        jPanel1.add(txtDespesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 72, -1));

        label3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label3.setText("Reduzida");
        jPanel1.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, 15));
        jPanel1.add(txtReduzida, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 72, -1));

        label4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label4.setText("Programa");
        jPanel1.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 15));
        jPanel1.add(txtPrograma, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 160, -1));

        label5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label5.setText("Cod. Aplicação");
        jPanel1.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 15));
        jPanel1.add(txtAplicacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 160, -1));

        rbNovo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        rbNovo.setText("Novo");
        rbNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbNovoMouseClicked(evt);
            }
        });
        rbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNovoActionPerformed(evt);
            }
        });
        jPanel1.add(rbNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 68, 41));

        rbAlterar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        rbAlterar.setText("Alterar");
        rbAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbAlterarMouseClicked(evt);
            }
        });
        rbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAlterarActionPerformed(evt);
            }
        });
        jPanel1.add(rbAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 68, 41));

        rbExcluir.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        rbExcluir.setText("Excluir");
        rbExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbExcluirMouseClicked(evt);
            }
        });
        rbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(rbExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, 41));

        buttonOK.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        buttonOK.setText("OK");
        buttonOK.setEnabled(false);
        buttonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOKActionPerformed(evt);
            }
        });
        jPanel1.add(buttonOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 84, -1));

        buttonCancelar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        buttonCancelar.setText("Cancelar");
        buttonCancelar.setEnabled(false);
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(buttonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 84, -1));

        buttonSair.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        buttonSair.setText("Sair");
        buttonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSairActionPerformed(evt);
            }
        });
        jPanel1.add(buttonSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 84, -1));

        buttonExcluir.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        buttonExcluir.setText("Excluir");
        buttonExcluir.setEnabled(false);
        buttonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(buttonExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 84, -1));

        buttonAlterar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        buttonAlterar.setText("Alterar");
        buttonAlterar.setEnabled(false);
        buttonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAlterarActionPerformed(evt);
            }
        });
        jPanel1.add(buttonAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 84, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setName(""); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label6.setText("Código");
        jPanel2.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 20, -1, 15));

        txtCodigoPesquisa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodigoPesquisaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodigoPesquisaFocusLost(evt);
            }
        });
        txtCodigoPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoPesquisaActionPerformed(evt);
            }
        });
        txtCodigoPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoPesquisaKeyPressed(evt);
            }
        });
        jPanel2.add(txtCodigoPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 40, 72, -1));

        label7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label7.setText("Desdobrada");
        jPanel2.add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 70, -1, 15));

        txtDespesaPesquisa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDespesaPesquisaFocusGained(evt);
            }
        });
        txtDespesaPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDespesaPesquisaActionPerformed(evt);
            }
        });
        txtDespesaPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDespesaPesquisaKeyPressed(evt);
            }
        });
        jPanel2.add(txtDespesaPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 90, 72, -1));

        label8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label8.setText("Reduzida");
        jPanel2.add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 70, -1, 15));

        txtReduzidaPesquisa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtReduzidaPesquisaFocusGained(evt);
            }
        });
        txtReduzidaPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReduzidaPesquisaActionPerformed(evt);
            }
        });
        txtReduzidaPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtReduzidaPesquisaKeyPressed(evt);
            }
        });
        jPanel2.add(txtReduzidaPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 90, 72, -1));

        label9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label9.setText("Programa");
        jPanel2.add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 120, -1, 15));

        txtProgramaPesquisa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtProgramaPesquisaFocusGained(evt);
            }
        });
        txtProgramaPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProgramaPesquisaActionPerformed(evt);
            }
        });
        txtProgramaPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtProgramaPesquisaKeyPressed(evt);
            }
        });
        jPanel2.add(txtProgramaPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 140, 162, -1));

        label10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label10.setText("Cod. Aplicação");
        jPanel2.add(label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 170, -1, 15));

        txtAplicacaoPesquisa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAplicacaoPesquisaFocusGained(evt);
            }
        });
        txtAplicacaoPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAplicacaoPesquisaKeyPressed(evt);
            }
        });
        jPanel2.add(txtAplicacaoPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 190, 162, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Pesquisas");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, 30));

        javax.swing.GroupLayout panelPesquisaLayout = new javax.swing.GroupLayout(panelPesquisa);
        panelPesquisa.setLayout(panelPesquisaLayout);
        panelPesquisaLayout.setHorizontalGroup(
            panelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPesquisaLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPesquisaLayout.setVerticalGroup(
            panelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(panelPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 39, 670, 440));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("DESPESAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 12, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOKActionPerformed

        // foi tornado global para não ter que declarar novamente
        // ModelDespesa despesa = new ModelDespesa();
        //despesa.setCodDespesa(Integer.valueOf(txtCodigo.getText()));
        despesa.setDespesa(txtDespesa.getText());
        despesa.setReduzida(txtReduzida.getText());
        despesa.setPrograma(txtPrograma.getText());
        despesa.setAplicacao(txtAplicacao.getText());

        // Condição que controla qual método vai ser utilizado dependendo do radio button  selecionado.
        if (rbNovo.isSelected()) {
            des.InserirDespesa(despesa);
        } else if (rbExcluir.isSelected()) {
            if (!"".equals(txtCodigo.getText())) {
                despesa.setCodDespesa(Integer.valueOf(txtCodigo.getText()));
                des.ExcluirDespesa(despesa);
            } else {
                JOptionPane.showMessageDialog(null, "Escolha na tabela o item a ser excluído.");
            }
        } else {
            if (!"".equals(txtCodigo.getText())) {
                despesa.setCodDespesa(Integer.valueOf(txtCodigo.getText()));
                des.AlterarDespesa(despesa);
            } else {
                JOptionPane.showMessageDialog(null, "Escolha na tabela o item a ser alterado.");
            }
        }
    }//GEN-LAST:event_buttonOKActionPerformed

    private void rbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNovoActionPerformed
        // TODO add your handling code here:
        desabilitaRbButtons();
        habilitaCamposdeTexto();
    }//GEN-LAST:event_rbNovoActionPerformed

    private void txtDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDespesaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtDespesaActionPerformed

    private void buttonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExcluirActionPerformed

        //despesa.setCodDespesa(Integer.valueOf(txtCodigo.getText()));
        //ControllerDespesa des = new ControllerDespesa();
        despesa.setCodDespesa(Integer.valueOf(txtCodigo.getText()));
        despesa.setDespesa(txtDespesa.getText());
        despesa.setReduzida(txtReduzida.getText());
        despesa.setPrograma(txtPrograma.getText());
        despesa.setAplicacao(txtAplicacao.getText());

        des.ExcluirDespesa(despesa);
    }//GEN-LAST:event_buttonExcluirActionPerformed

    private void buttonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAlterarActionPerformed
        // TODO add your handling code here:
        despesa.setCodDespesa(Integer.valueOf(txtCodigo.getText()));
        despesa.setDespesa(txtDespesa.getText());
        despesa.setReduzida(txtReduzida.getText());
        despesa.setPrograma(txtPrograma.getText());
        despesa.setAplicacao(txtAplicacao.getText());

        des.AlterarDespesa(despesa);

    }//GEN-LAST:event_buttonAlterarActionPerformed

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
        // TODO add your handling code here:
        habilitaRbButtons();
        LimpaCamposTexto();
        desabilitaCamposdeTexto();
        desmarcarRbButtons();

    }//GEN-LAST:event_buttonCancelarActionPerformed

    private void rbNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbNovoMouseClicked
        // TODO add your handling code here:
        rbExcluir.setSelected(false);
        rbAlterar.setSelected(false);
        buttonOK.setEnabled(true);
        buttonCancelar.setEnabled(true);
    }//GEN-LAST:event_rbNovoMouseClicked

    private void rbExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbExcluirMouseClicked
        // TODO add your handling code here:
        //desabilitaDemaisRbButtons();
        rbNovo.setSelected(false);
        rbAlterar.setSelected(false);
        buttonOK.setEnabled(true);
        buttonCancelar.setEnabled(true);
    }//GEN-LAST:event_rbExcluirMouseClicked

    private void rbAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbAlterarMouseClicked
        // TODO add your handling code here:
        //desabilitaDemaisRbButtons();
        rbExcluir.setSelected(false);
        rbNovo.setSelected(false);
        buttonOK.setEnabled(true);
        buttonCancelar.setEnabled(true);
    }//GEN-LAST:event_rbAlterarMouseClicked

    private void rbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbExcluirActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Dê duplo clique com o mouse na linha da tabela acima \n correspondente à despesa que você quer excluir");
        desabilitaRbButtons();
        buttonOK.setEnabled(true);
        buttonCancelar.setEnabled(true);
    }//GEN-LAST:event_rbExcluirActionPerformed

    private void rbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAlterarActionPerformed
        // TODO add your handling code here:
        desabilitaRbButtons();
        habilitaCamposdeTexto();
    }//GEN-LAST:event_rbAlterarActionPerformed

    private void buttonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_buttonSairActionPerformed

    private void txtDespesaPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDespesaPesquisaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtDespesaPesquisaActionPerformed

    private void jTableDespesaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDespesaMouseClicked
        try {
            // TODO add your handling code here:
            //Preenche os Campos de Texto correspondentes ao clicar numa linha do JTable
            String codigodadespesa = "" + jTableDespesa.getValueAt(jTableDespesa.getSelectedRow(), 0);
            conecta.conexao();
            conecta.executaSQL("Select * from dotacao where cod_despesa='" + codigodadespesa + "'");
            conecta.rs.first();
            txtCodigo.setText(String.valueOf(conecta.rs.getInt("Cod_despesa")));
            txtDespesa.setText(String.valueOf(conecta.rs.getString("Despesa")));
            txtReduzida.setText(String.valueOf(conecta.rs.getString("Reduzida")));
            txtPrograma.setText(String.valueOf(conecta.rs.getString("Programa")));
            txtAplicacao.setText(String.valueOf(conecta.rs.getString("Acao")));
            //conecta.desconectar();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao capturar dados da linha selecionada [" + ex);
        }

    }//GEN-LAST:event_jTableDespesaMouseClicked

    private void txtCodigoPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoPesquisaKeyPressed
        
        preencherTabela("Select * From dotacao order by cod_despesa");   
        
        habilitaCamposdeTexto();
        String pesquisarnome = txtCodigoPesquisa.getText();
        //JOptionPane.showMessageDialog(null, pesquisarnome);
        
        if (pesquisarnome.length() > 0) {
            for (int i = 0; i < jTableDespesa.getRowCount(); i++) {
                if (!pesquisarnome.equals(jTableDespesa.getValueAt(i, 0).toString())) {
                } else {
                    //JOptionPane.showMessageDialog(null,jTableDespesa.getValueAt(i, 0).toString() );
                    //txtCodigo.setText(jTableDespesa.getValueAt(i, 0).toString());
                    //txtDespesa.setText(jTableDespesa.getValueAt(i, 1).toString());
                    //txtReduzida.setText(jTableDespesa.getValueAt(i, 2).toString());
                    //txtPrograma.setText(jTableDespesa.getValueAt(i, 3).toString());
                    //txtAplicacao.setText(jTableDespesa.getValueAt(i, 4).toString());
                    preencherTabela("Select * From dotacao where Cod_despesa='" + pesquisarnome +"'");
                }
            }
        }
    }//GEN-LAST:event_txtCodigoPesquisaKeyPressed

    private void txtCodigoPesquisaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoPesquisaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoPesquisaFocusLost

    private void txtDespesaPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDespesaPesquisaKeyPressed
        // TODO add your handling code here:
        //if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        preencherTabela("Select * From dotacao order by cod_despesa");   
        
        habilitaCamposdeTexto();
        String pesquisadespesa = txtDespesaPesquisa.getText();
        //JOptionPane.showMessageDialog(null, pesquisarnome);
        
        if (pesquisadespesa.length() > 0) {
            for (int i = 0; i < jTableDespesa.getRowCount(); i++) {
                if (!pesquisadespesa.equals(jTableDespesa.getValueAt(i, 1).toString())) {
                    
                    preencherTabela("Select * From dotacao where despesa=''");
                    
                } else {
                    //JOptionPane.showMessageDialog(null,jTableDespesa.getValueAt(i, 0).toString() );
                    //txtCodigo.setText(jTableDespesa.getValueAt(i, 0).toString());
                    //txtDespesa.setText(jTableDespesa.getValueAt(i, 1).toString());
                    //txtReduzida.setText(jTableDespesa.getValueAt(i, 2).toString());
                    //txtPrograma.setText(jTableDespesa.getValueAt(i, 3).toString());
                    //txtAplicacao.setText(jTableDespesa.getValueAt(i, 4).toString());
                    preencherTabela("Select * From dotacao where despesa='" + pesquisadespesa +"'");
                }
            }
        }
    }//GEN-LAST:event_txtDespesaPesquisaKeyPressed

    private void txtReduzidaPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReduzidaPesquisaActionPerformed
        
        
    }//GEN-LAST:event_txtReduzidaPesquisaActionPerformed

    private void txtProgramaPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProgramaPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProgramaPesquisaActionPerformed

    private void txtProgramaPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProgramaPesquisaKeyPressed
        
        preencherTabela("Select * From dotacao order by cod_despesa");   
        habilitaCamposdeTexto();
        String pesquisaprograma = txtProgramaPesquisa.getText();
        //JOptionPane.showMessageDialog(null, pesquisarnome);
        
        if (pesquisaprograma.length() > 0) {
            for (int i = 0; i < jTableDespesa.getRowCount(); i++) {
                if (!pesquisaprograma.equals(jTableDespesa.getValueAt(i, 3).toString())) {
                } else {
                    //JOptionPane.showMessageDialog(null,jTableDespesa.getValueAt(i, 0).toString() );
                    //txtCodigo.setText(jTableDespesa.getValueAt(i, 0).toString());
                    //txtDespesa.setText(jTableDespesa.getValueAt(i, 1).toString());
                    //txtReduzida.setText(jTableDespesa.getValueAt(i, 2).toString());
                    //txtPrograma.setText(jTableDespesa.getValueAt(i, 3).toString());
                    //txtAplicacao.setText(jTableDespesa.getValueAt(i, 4).toString());
                    preencherTabela("Select * From dotacao where programa='" + pesquisaprograma +"'");
                }
            }
        }
    }//GEN-LAST:event_txtProgramaPesquisaKeyPressed

    private void txtReduzidaPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtReduzidaPesquisaKeyPressed
        // TODO add your handling code here:
        preencherTabela("Select * From dotacao order by cod_despesa");   
        
        habilitaCamposdeTexto();
        String pesquisareduzida = txtReduzidaPesquisa.getText();
        //JOptionPane.showMessageDialog(null, pesquisarnome);
        
        if (pesquisareduzida.length() > 0) {
            for (int i = 0; i < jTableDespesa.getRowCount(); i++) {
                if (!pesquisareduzida.equals(jTableDespesa.getValueAt(i, 2).toString())) {
                } else {
                    //JOptionPane.showMessageDialog(null,jTableDespesa.getValueAt(i, 0).toString() );
                    //txtCodigo.setText(jTableDespesa.getValueAt(i, 0).toString());
                    //txtDespesa.setText(jTableDespesa.getValueAt(i, 1).toString());
                    //txtReduzida.setText(jTableDespesa.getValueAt(i, 2).toString());
                    //txtPrograma.setText(jTableDespesa.getValueAt(i, 3).toString());
                    //txtAplicacao.setText(jTableDespesa.getValueAt(i, 4).toString());
                    preencherTabela("Select * From dotacao where reduzida='" + pesquisareduzida +"'");
                }
            }
        }
    }//GEN-LAST:event_txtReduzidaPesquisaKeyPressed

    private void txtAplicacaoPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAplicacaoPesquisaKeyPressed
        
        preencherTabela("Select * From dotacao order by cod_despesa");   
        
        habilitaCamposdeTexto();
        String pesquisaaplicacao = txtAplicacaoPesquisa.getText();
        //JOptionPane.showMessageDialog(null, pesquisarnome);
        
        if (pesquisaaplicacao.length() > 0) {
            for (int i = 0; i < jTableDespesa.getRowCount(); i++) {
                if (!pesquisaaplicacao.equals(jTableDespesa.getValueAt(i, 4).toString())) {
                } else {
                    //JOptionPane.showMessageDialog(null,jTableDespesa.getValueAt(i, 0).toString() );
                    //txtCodigo.setText(jTableDespesa.getValueAt(i, 0).toString());
                    //txtDespesa.setText(jTableDespesa.getValueAt(i, 1).toString());
                    //txtReduzida.setText(jTableDespesa.getValueAt(i, 2).toString());
                    //txtPrograma.setText(jTableDespesa.getValueAt(i, 3).toString());
                    //txtAplicacao.setText(jTableDespesa.getValueAt(i, 4).toString());
                    preencherTabela("Select * From dotacao where acao='" + pesquisaaplicacao +"'");
                }
            }
        }
    }//GEN-LAST:event_txtAplicacaoPesquisaKeyPressed

    private void txtCodigoPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoPesquisaActionPerformed

    private void txtCodigoPesquisaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoPesquisaFocusGained
        // TODO add your handling code here:
        //txtCodigoPesquisa.setText("");
        txtDespesaPesquisa.setText("");
        txtProgramaPesquisa.setText("");
        txtAplicacaoPesquisa.setText("");
        txtReduzidaPesquisa.setText("");
    }//GEN-LAST:event_txtCodigoPesquisaFocusGained

    private void txtDespesaPesquisaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDespesaPesquisaFocusGained
        // TODO add your handling code here:
        txtCodigoPesquisa.setText("");
        //txtDespesaPesquisa.setText("");
        txtProgramaPesquisa.setText("");
        txtAplicacaoPesquisa.setText("");
        txtReduzidaPesquisa.setText("");
    }//GEN-LAST:event_txtDespesaPesquisaFocusGained

    private void txtReduzidaPesquisaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtReduzidaPesquisaFocusGained
        // TODO add your handling code here:
        txtCodigoPesquisa.setText("");
        txtDespesaPesquisa.setText("");
        txtProgramaPesquisa.setText("");
        txtAplicacaoPesquisa.setText("");
        //txtReduzidaPesquisa.setText("");
    }//GEN-LAST:event_txtReduzidaPesquisaFocusGained

    private void txtProgramaPesquisaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtProgramaPesquisaFocusGained
        // TODO add your handling code here:
        txtCodigoPesquisa.setText("");
        txtDespesaPesquisa.setText("");
        //txtProgramaPesquisa.setText("");
        txtAplicacaoPesquisa.setText("");
        txtReduzidaPesquisa.setText("");
    }//GEN-LAST:event_txtProgramaPesquisaFocusGained

    private void txtAplicacaoPesquisaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAplicacaoPesquisaFocusGained
        // TODO add your handling code here:
        txtCodigoPesquisa.setText("");
        txtDespesaPesquisa.setText("");
        txtProgramaPesquisa.setText("");
        //txtAplicacaoPesquisa.setText("");
        txtReduzidaPesquisa.setText("");
    }//GEN-LAST:event_txtAplicacaoPesquisaFocusGained

    public void preencherTabela(String SQL) {

        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Código", "Despesa", "Reduzida", "Programa", "Cod.Aplicacão"};

        conecta.executaSQL(SQL);

        try {
            conecta.rs.first();
            do {
                dados.add(new Object[]{conecta.rs.getInt("Cod_Despesa"), conecta.rs.getString("Despesa"), conecta.rs.getString("Reduzida"), conecta.rs.getString("Programa"), conecta.rs.getString("Acao")});
            } while (conecta.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Informação não encontrada.\n" + ex.getMessage());
        }

        //Criando a Tabela
        ModelTabela modelo = new ModelTabela(dados, colunas);
        jTableDespesa.setModel(modelo);
        jTableDespesa.getColumnModel().getColumn(0).setPreferredWidth(120);
        jTableDespesa.getColumnModel().getColumn(0).setResizable(false);
        jTableDespesa.getColumnModel().getColumn(1).setPreferredWidth(120);
        jTableDespesa.getColumnModel().getColumn(1).setResizable(false);
        jTableDespesa.getColumnModel().getColumn(2).setPreferredWidth(120);
        jTableDespesa.getColumnModel().getColumn(2).setResizable(false);
        jTableDespesa.getColumnModel().getColumn(3).setPreferredWidth(120);
        jTableDespesa.getColumnModel().getColumn(3).setResizable(false);
        jTableDespesa.getColumnModel().getColumn(4).setPreferredWidth(120);
        jTableDespesa.getColumnModel().getColumn(4).setResizable(false);
        jTableDespesa.getTableHeader().setReorderingAllowed(false);
        jTableDespesa.setAutoResizeMode(jTableDespesa.AUTO_RESIZE_OFF);
        jTableDespesa.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameDespesa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAlterar;
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JButton buttonExcluir;
    private javax.swing.JButton buttonOK;
    private javax.swing.JButton buttonSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableDespesa;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private java.awt.Panel panelPesquisa;
    private javax.swing.JRadioButton rbAlterar;
    private javax.swing.JRadioButton rbExcluir;
    private javax.swing.JRadioButton rbNovo;
    private java.awt.TextField txtAplicacao;
    private java.awt.TextField txtAplicacaoPesquisa;
    private java.awt.TextField txtCodigo;
    private java.awt.TextField txtCodigoPesquisa;
    private java.awt.TextField txtDespesa;
    private java.awt.TextField txtDespesaPesquisa;
    private java.awt.TextField txtPrograma;
    private java.awt.TextField txtProgramaPesquisa;
    private java.awt.TextField txtReduzida;
    private java.awt.TextField txtReduzidaPesquisa;
    // End of variables declaration//GEN-END:variables

    private void desabilitaRbButtons() {

        rbNovo.setEnabled(false);
        rbExcluir.setEnabled(false);
        rbAlterar.setEnabled(false);

    }

    private void habilitaRbButtons() {
        rbNovo.setEnabled(true);
        rbExcluir.setEnabled(true);
        rbAlterar.setEnabled(true);
    }

    private void desabilitaCamposdeTexto() {
        txtCodigo.setEnabled(false);
        txtDespesa.setEnabled(false);
        txtReduzida.setEnabled(false);
        txtPrograma.setEnabled(false);
        txtAplicacao.setEnabled(false);
    }

    private void habilitaCamposdeTexto() {

        txtCodigo.setEnabled(true);
        txtDespesa.setEnabled(true);
        txtReduzida.setEnabled(true);
        txtPrograma.setEnabled(true);
        txtAplicacao.setEnabled(true);
    }

    private void LimpaCamposTexto() {

        txtCodigo.setText("");
        txtDespesa.setText("");
        txtPrograma.setText("");
        txtAplicacao.setText("");
        txtReduzida.setText("");
    }

    private void desmarcarRbButtons() {

        rbNovo.setSelected(false);
        rbExcluir.setSelected(false);
        rbAlterar.setSelected(false);
    }
}
