/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ConnectionDB;
import controller.ControllerDespesa;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import model.ModelDespesa;
import controller.ModelTabela;
import java.sql.ResultSet;

/**
 *
 * @author Marco Antonio
 */
public class JFrameDespesa extends javax.swing.JFrame {

    //ConnectionDB conexao = new ConnectionDB();
    //ControllerDespesa desp = new ControllerDespesa();
    ConnectionDB conecta = new ConnectionDB();
    ModelDespesa despesa = new ModelDespesa();// foi tornado global para não ter que instanciar novamente
    ControllerDespesa des = new ControllerDespesa();

// novamente no botão excluir.
    /**
     * Creates new form JFrameDespesa
     */
    public JFrameDespesa() {
        initComponents();
        //conexao.conectar();
        conecta.conexao();
        preencherTabela("select * from dotacao order by Cod_Despesa");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panel1 = new java.awt.Panel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDespesa = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        txtCodigo = new java.awt.TextField();
        label2 = new java.awt.Label();
        txtDespesa = new java.awt.TextField();
        label3 = new java.awt.Label();
        txtReduzida = new java.awt.TextField();
        label4 = new java.awt.Label();
        txtPrograma = new java.awt.TextField();
        label5 = new java.awt.Label();
        txtAplicacao = new java.awt.TextField();
        rbNovo = new javax.swing.JRadioButton();
        rbAlterar = new javax.swing.JRadioButton();
        rbExcluir = new javax.swing.JRadioButton();
        buttonOK = new javax.swing.JButton();
        buttonCancelar = new javax.swing.JButton();
        buttonSair = new javax.swing.JButton();
        buttonExcluir = new javax.swing.JButton();
        buttonAlterar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Despesas");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableDespesa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTableDespesa);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label1.setText("Código");
        jPanel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        txtCodigo.setEnabled(false);
        jPanel1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 72, -1));

        label2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label2.setText("Desdobrada");
        jPanel1.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        txtDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDespesaActionPerformed(evt);
            }
        });
        jPanel1.add(txtDespesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 72, -1));

        label3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label3.setText("Reduzida");
        jPanel1.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));
        jPanel1.add(txtReduzida, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 72, -1));

        label4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label4.setText("Programa");
        jPanel1.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));
        jPanel1.add(txtPrograma, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 155, -1));

        label5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label5.setText("Cod. Aplicação");
        jPanel1.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));
        jPanel1.add(txtAplicacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 155, -1));

        rbNovo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        rbNovo.setText("Novo");
        rbNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbNovoMouseClicked(evt);
            }
        });
        rbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNovoActionPerformed(evt);
            }
        });
        jPanel1.add(rbNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 68, 41));

        rbAlterar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        rbAlterar.setText("Alterar");
        rbAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbAlterarMouseClicked(evt);
            }
        });
        rbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAlterarActionPerformed(evt);
            }
        });
        jPanel1.add(rbAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 68, 41));

        rbExcluir.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        rbExcluir.setText("Excluir");
        rbExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbExcluirMouseClicked(evt);
            }
        });
        rbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(rbExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, -1, 41));

        buttonOK.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        buttonOK.setText("OK");
        buttonOK.setEnabled(false);
        buttonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOKActionPerformed(evt);
            }
        });
        jPanel1.add(buttonOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 84, -1));

        buttonCancelar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        buttonCancelar.setText("Cancelar");
        buttonCancelar.setEnabled(false);
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(buttonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 90, -1));

        buttonSair.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        buttonSair.setText("Sair");
        buttonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSairActionPerformed(evt);
            }
        });
        jPanel1.add(buttonSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 80, -1));

        buttonExcluir.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        buttonExcluir.setText("Excluir");
        buttonExcluir.setEnabled(false);
        buttonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(buttonExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 84, -1));

        buttonAlterar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        buttonAlterar.setText("Alterar");
        buttonAlterar.setEnabled(false);
        buttonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAlterarActionPerformed(evt);
            }
        });
        jPanel1.add(buttonAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 84, -1));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        panel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel1, jScrollPane2});

        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 39, -1, 457));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("DESPESAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 12, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOKActionPerformed

        // foi tornado global para não ter que declarar novamente
        // ModelDespesa despesa = new ModelDespesa();
        //despesa.setCodDespesa(Integer.valueOf(txtCodigo.getText()));
        despesa.setDespesa(txtDespesa.getText());
        despesa.setReduzida(txtReduzida.getText());
        despesa.setPrograma(txtPrograma.getText());
        despesa.setAplicacao(txtAplicacao.getText());

        des.InserirDespesa(despesa);
    }//GEN-LAST:event_buttonOKActionPerformed

    private void rbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNovoActionPerformed
        // TODO add your handling code here:
        desabilitaRbButtons();
    }//GEN-LAST:event_rbNovoActionPerformed

    private void txtDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDespesaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtDespesaActionPerformed

    private void buttonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExcluirActionPerformed

        //despesa.setCodDespesa(Integer.valueOf(txtCodigo.getText()));
        //ControllerDespesa des = new ControllerDespesa();
        despesa.setCodDespesa(Integer.valueOf(txtCodigo.getText()));
        despesa.setDespesa(txtDespesa.getText());
        despesa.setReduzida(txtReduzida.getText());
        despesa.setPrograma(txtPrograma.getText());
        despesa.setAplicacao(txtAplicacao.getText());

        des.ExcluirDespesa(despesa);
    }//GEN-LAST:event_buttonExcluirActionPerformed

    private void buttonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAlterarActionPerformed
        // TODO add your handling code here:
        despesa.setCodDespesa(Integer.valueOf(txtCodigo.getText()));
        despesa.setDespesa(txtDespesa.getText());
        despesa.setReduzida(txtReduzida.getText());
        despesa.setPrograma(txtPrograma.getText());
        despesa.setAplicacao(txtAplicacao.getText());

        des.AlterarDespesa(despesa);

    }//GEN-LAST:event_buttonAlterarActionPerformed

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
        // TODO add your handling code here:
        habilitaRbButtons();

    }//GEN-LAST:event_buttonCancelarActionPerformed

    private void rbNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbNovoMouseClicked
        // TODO add your handling code here:
        rbExcluir.setSelected(false);
        rbAlterar.setSelected(false);
        buttonOK.setEnabled(true);
        buttonCancelar.setEnabled(true);
    }//GEN-LAST:event_rbNovoMouseClicked

    private void rbExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbExcluirMouseClicked
        // TODO add your handling code here:
        //desabilitaDemaisRbButtons();
        rbNovo.setSelected(false);
        rbAlterar.setSelected(false);
        buttonOK.setEnabled(true);
        buttonCancelar.setEnabled(true);
    }//GEN-LAST:event_rbExcluirMouseClicked

    private void rbAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbAlterarMouseClicked
        // TODO add your handling code here:
        //desabilitaDemaisRbButtons();
        rbExcluir.setSelected(false);
        rbNovo.setSelected(false);
        buttonOK.setEnabled(true);
        buttonCancelar.setEnabled(true);
    }//GEN-LAST:event_rbAlterarMouseClicked

    private void rbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbExcluirActionPerformed
        // TODO add your handling code here:
        desabilitaRbButtons();
    }//GEN-LAST:event_rbExcluirActionPerformed

    private void rbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAlterarActionPerformed
        // TODO add your handling code here:
        desabilitaRbButtons();
    }//GEN-LAST:event_rbAlterarActionPerformed

    private void buttonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_buttonSairActionPerformed

    public void preencherTabela(String SQL) {

        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Código", "Despesa", "Reduzida", "Programa", "Cod.Aplicacão"};

        conecta.executaSQL(SQL);

        try {
            conecta.rs.first();
            do {
                dados.add(new Object[]{conecta.rs.getInt("Cod_Despesa"), conecta.rs.getString("Despesa"), conecta.rs.getString("Reduzida"), conecta.rs.getString("Programa"), conecta.rs.getString("Acao")});
            } while (conecta.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao preencher o ArrayList!\n " + ex.getMessage());
        }

        //Criando a Tabela
        ModelTabela modelo = new ModelTabela(dados, colunas);
        jTableDespesa.setModel(modelo);
        jTableDespesa.getColumnModel().getColumn(0).setPreferredWidth(120);
        jTableDespesa.getColumnModel().getColumn(0).setResizable(false);
        jTableDespesa.getColumnModel().getColumn(1).setPreferredWidth(120);
        jTableDespesa.getColumnModel().getColumn(1).setResizable(false);
        jTableDespesa.getColumnModel().getColumn(2).setPreferredWidth(120);
        jTableDespesa.getColumnModel().getColumn(2).setResizable(false);
        jTableDespesa.getColumnModel().getColumn(3).setPreferredWidth(120);
        jTableDespesa.getColumnModel().getColumn(3).setResizable(false);
        jTableDespesa.getColumnModel().getColumn(4).setPreferredWidth(120);
        jTableDespesa.getColumnModel().getColumn(4).setResizable(false);
        jTableDespesa.getTableHeader().setReorderingAllowed(false);
        jTableDespesa.setAutoResizeMode(jTableDespesa.AUTO_RESIZE_OFF);
        jTableDespesa.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameDespesa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAlterar;
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JButton buttonExcluir;
    private javax.swing.JButton buttonOK;
    private javax.swing.JButton buttonSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableDespesa;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Panel panel1;
    private javax.swing.JRadioButton rbAlterar;
    private javax.swing.JRadioButton rbExcluir;
    private javax.swing.JRadioButton rbNovo;
    private java.awt.TextField txtAplicacao;
    private java.awt.TextField txtCodigo;
    private java.awt.TextField txtDespesa;
    private java.awt.TextField txtPrograma;
    private java.awt.TextField txtReduzida;
    // End of variables declaration//GEN-END:variables

    private void desabilitaRbButtons() {

        rbNovo.setEnabled(false);
        rbExcluir.setEnabled(false);
        rbAlterar.setEnabled(false);

    }

    private void habilitaRbButtons() {

        rbNovo.setEnabled(true);
        rbExcluir.setEnabled(true);
        rbAlterar.setEnabled(true);

    }

}
